export enum InvoiceBuilderEnumURLs {
    Invoice_builder_List_Post = 'invoice/add',
    Invoice_builder_List_Get = 'invoice/all',
    Invoice_builder_List_Put = 'invoice/update',
    Invoice_builder_List_Delete = 'invoice/delete',
    Single_Invoice_builder_Get = 'invoice/single',
    Invoice_builder_chart_Id = 'invoice/chart/ids/all',
    Invoice_builder_case_Id = 'invoice/case/ids/all',
	Invoice_builder_get_pdf = 'invoice/get/pdf',
    Invoice_builder_facility_Location = 'invoice/facility/location',
    Invoice_builder_Employer_details = 'all_employer',
    Invoice_builder_Attorney_details = 'attorney_list',
    Invoice_builder_Invoice_to = 'invoice/to/details',
    Invoice_builder_Insurance_Loc = 'invoice/insurance-locations',
    Invoice_builder_Firm_Loc = 'invoice/firm-locations',
    Invoice_builder_Bill_DOS_GET = 'bill/get/dos-range',
    Invoice_builder_Invoice_Post = 'invoice/save/details',
	Invoice_builder_Invoice_Type_Category = 'invoice/categories/all',
	Invoice_builder_get_billing_Data = 'invoice/get/invoiceDetails',
    Invoice_builder_get_bill_visitSession = 'bill/get/detail',
    get_bills_of_specilities='bill/get-specialty-bills',
    get_bills_specilities='bill/get-bills-specialty',
}
