export enum TemplateMasterUrlEnum {
  getRequiredFieldsList = "fields_controls",
  getRoles = 'roles',
  getRoleSpeciality = 'get_role_specialities_with_fields_controls',
  postAttachFieldControlsToRole = 'attach_fields_controls_to_role',
  getFacilitiesLocations = 'get_facilities_locations',
  specialities = 'specialities',
  getFieldsControlsWithIsRequired = 'get_fields_controls_with_is_required?',
  addHFPermissions = 'addHFPermissions/',
  getHFPermissions = 'getHFPermissions/',
  deleteHFPermissions = 'deleteHFPermissions/',
  getHeaderFooter = 'getHeaderFooter/',
  deleteHeaderFooter = 'deleteHeaderFooter/',
  updateHFPermissions = 'updateHFPermissions/',
  addHeaderFooter = 'addHeaderFooter/',
  getUIComponentsBySection='getUIComponentsBySection/',
  uploadImage='uploadImage/',
  getAllFieldTags="fields_tags",
  getFacilitySpeciality='get_facility_location_specialities_with_fields_controls',
  postAttachFieldControlsToFacility='attach_fields_controls_to_facility_location',
  Facility_list_dropdown_GET = 'facilities_locations',
  FieldTagUpdate ="fields_tag/update",
}
