export class PatientProfileMockValues{
	 ResutGetPatient = {
		result: {
			data: [
				{
					creation_source_string: 'Web',
					id: 1,
					key: null,
					first_name: 'ali',
					middle_name: 'm',
					last_name: 'raza',
					dob: '2021-07-07',
					gender: 'x',
					age: null,
					ssn: null,
					cell_phone: '4444444444',
					home_phone: '1111111111',
					work_phone: null,
					height_ft: null,
					height_in: null,
					weight_lbs: null,
					weight_kg: null,
					meritial_status: null,
					profile_avatar: null,
					need_translator: 0,
					language: null,
					is_pregnant: null,
					is_law_enforcement_agent: null,
					status: 'open',
					notes: null,
					user_id: null,
					by_health_app: 0,
					creation_source: 1,
					created_by: null,
					updated_by: null,
					created_at: '2021-07-08T13:26:50.000Z',
					updated_at: '2021-07-08T13:26:50.000Z',
					deleted_at: null,
					pharmacy: [],
					self: {
						contact_information: {
							mail_address: {
								id: 1,
								key: null,
								contact_person_id: 1,
								type: 'mailing',
								street: '334 Amboy Ave',
								apartment: '123213123123123',
								latitude: null,
								longitude: null,
								city: 'Woodbridge Township',
								state: 'NJ',
								zip: '70950-1111',
								created_by: null,
								updated_by: null,
								created_at: '2021-07-08T13:26:50.000Z',
								updated_at: '2021-07-08T13:26:50.000Z',
								deleted_at: null,
							},
							residential_address: null,
						},
						id: 1,
						key: null,
						case_id: null,
						contact_person_type_id: 1,
						contact_person_relation_id: null,
						other_relation_description: null,
						first_name: null,
						middle_name: null,
						last_name: null,
						ssn: null,
						dob: null,
						age: null,
						gender: null,
						email: 'email@email.email',
						fax: null,
						cell_phone: '4444444444',
						home_phone: '1111111111',
						work_phone: null,
						ext: null,
						height_in: null,
						height_ft: null,
						weight_lbs: null,
						weight_kg: null,
						marital_status: null,
						is_resedential_same: null,
						is_form_filler: null,
						is_emergency: null,
						is_guarantor: null,
						workplace_name: null,
						object_id: 1,
						created_by: null,
						updated_by: null,
						created_at: '2021-07-08T13:26:50.000Z',
						updated_at: '2021-07-08T13:26:50.000Z',
						deleted_at: null,
					},
					emergency: {
						contact_person_relation: {
							name: 'Emeregeny Name',
						},
					},
					chart_id: '000-00-0001',
				},
			]
		},
	};
	patientResponce = {
		id: 1123,
		first_name: 'first_name',
		middle_name: 'middle_name',
		last_name: 'last_name',
		gender: 'gender',
		dob: '2020-11-25',
		ssn: '111-111-111',
		self: {
			id: 21,
			home_phone: 'home_phone',
			work_phone: 'work_phone',
			cell_phone: 'cell_phone',
			email: 'admin@ovada.com',
			contact_information: {
				mail_address: {
					id: 45,
					street: 'street',
					apartment: 'apartment',
					city: 'city',
					state: 'state',
					zip: '12121212',
				},
			},
		},
	};
	tabSet = {
		tabs: [
			{
				id: 10,
				active: true,
			},
			{
				id: 25,
				active: false,
			},
		],
	};
	configFiels = [
		{
			allowed_case_type_slugs: [],
			onTypeahead$: {
				_isScalar: false,
				observers: [],
				closed: false,
				isStopped: false,
				hasError: false,
				thrownError: null,
			},
			element: 'div',
			children: [
				{
					allowed_case_type_slugs: [],
					onTypeahead$: {
						_isScalar: false,
						observers: [],
						closed: false,
						isStopped: false,
						hasError: false,
						thrownError: null,
					},
					element: 'div',
					children: [
						{
							allowed_case_type_slugs: [],
							onTypeahead$: {
								_isScalar: false,
								observers: [],
								closed: false,
								isStopped: false,
								hasError: false,
								thrownError: null,
							},
							element: 'div',
							children: [
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Case No.',
									name: 'id',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-6 col-md-4 col-lg-3 col-xl-2'],
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Case type',
									name: 'case_type',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-6 col-md-4 col-lg-3 col-xl-2'],
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Attorney',
									name: 'attorney_name',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-6 col-md-4 col-lg-3 col-xl-2'],
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Insurance',
									name: 'insurance_name',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-6 col-md-4 col-lg-3 col-xl-2'],
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'DOA (mm/dd/yyyy)',
									name: 'date_of_accident',
									type: 'date',
									values: '',
									validations: [
										{
											name: 'max_date',
											message: 'Max date should be 8/27/2021',
										},
									],
									style: '',
									classes: ['col-sm-6 col-md-4 col-lg-3 col-xl-2'],
									configs: {
										max: '2021-08-27T11:57:15.166Z',
									},
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Claim No.',
									name: 'claim_no',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-6 col-md-4 col-lg-3 col-xl-2'],
								},
							],
							classes: ['row'],
						},
					],
					classes: ['col-lg-12 col-xl-10'],
				},
				{
					allowed_case_type_slugs: [],
					onTypeahead$: {
						_isScalar: false,
						observers: [],
						closed: false,
						isStopped: false,
						hasError: false,
						thrownError: null,
					},
					element: 'div',
					children: [
						{
							allowed_case_type_slugs: [],
							onTypeahead$: {
								_isScalar: false,
								observers: [],
								closed: false,
								isStopped: false,
								hasError: false,
								thrownError: null,
							},
							element: 'div',
							children: [
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'button',
									label: 'Filter',
									classes: ['btn', 'btn-success w-100 float-right'],
									type: 'submit',
									configs: {
										button_classes: ['col-5 col-sm-3 col-lg-2 col-xl-6'],
									},
									onSubmit: null,
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'button',
									label: 'Reset',
									classes: ['btn', 'btn-primary w-100'],
									type: 'button',
									configs: {
										button_classes: ['col-5 col-sm-3 col-lg-2 col-xl-6'],
										disabled: true,
										name: 'resetBtn',
									},
								},
							],
							classes: ['row', 'justify-content-center mb-3 mb-xl-0'],
							values: '',
							style: '',
							configs: {
								name: 'button-div',
							},
						},
					],
					classes: ['col-lg-12 col-xl-2'],
				},
			],
			classes: ['row', 'dynamic-filter'],
		},
	];
	patientList = [
		{
			id: 779,
			key: null,
			first_name: 'Soloman',
			middle_name: '',
			last_name: 'Bergamel',
			dob: '1970-03-21',
			gender: 'male',
			age: null,
			ssn: '',
			cell_phone: '4345456565',
			home_phone: '',
			work_phone: '',
			height_ft: null,
			height_in: null,
			weight_lbs: null,
			weight_kg: null,
			meritial_status: null,
			profile_avatar: null,
			need_translator: null,
			language: null,
			is_pregnant: null,
			is_law_enforcement_agent: null,
			status: 'open',
			notes: null,
			user_id: null,
			by_health_app: 0,
			created_by: null,
			updated_by: null,
			created_at: '2021-05-08T10:01:57.000Z',
			updated_at: '2021-05-08T10:01:57.000Z',
			deleted_at: null,
			pharmacy: [],
			self: {
				contact_information: {
					mail_address: {
						id: 1933,
						key: null,
						contact_person_id: 2573,
						type: 'mailing',
						street: '1948 Bainbridge St',
						apartment: '',
						latitude: null,
						longitude: null,
						city: 'Philadelphia',
						state: 'PA',
						zip: '19146',
						created_by: null,
						updated_by: null,
						created_at: '2021-05-08T10:01:57.000Z',
						updated_at: '2021-05-08T10:01:57.000Z',
						deleted_at: null,
					},
					residential_address: null,
				},
				id: 2573,
				key: null,
				case_id: null,
				contact_person_type_id: 1,
				contact_person_relation_id: null,
				other_relation_description: null,
				first_name: null,
				middle_name: null,
				last_name: null,
				ssn: null,
				dob: null,
				age: null,
				gender: null,
				email: '',
				fax: null,
				cell_phone: '4345456565',
				home_phone: '',
				work_phone: '',
				ext: null,
				height_in: null,
				height_ft: null,
				weight_lbs: null,
				weight_kg: null,
				marital_status: null,
				is_resedential_same: null,
				is_form_filler: null,
				is_emergency: null,
				is_guarantor: null,
				workplace_name: null,
				object_id: 779,
				created_by: null,
				updated_by: null,
				created_at: '2021-05-08T10:01:57.000Z',
				updated_at: '2021-05-08T10:01:57.000Z',
				deleted_at: null,
			},
			emergency: null,
			chart_id: '000-00-0779',
		},
	];
}
