import { Injectable } from '@angular/core';
import { RequestService } from '@appDir/shared/services/request.service';
import { RoleServiceUrlEnums } from './RoleServiceUrlEnums';
import { REQUEST_SERVERS } from '@appDir/request-servers.enum';
import { getObjectChildValue, removeEmptyAndNullsFormObject } from '@appDir/shared/utils/utils.helpers';
@Injectable({
  providedIn: 'root'
})
export class RolesServiceService {

  constructor(protected requestService: RequestService) { }

  getAllRoles() {
    var requestData = { token: getObjectChildValue(JSON.parse(localStorage.getItem('data')), '', ['token']) }
    return this.requestService.sendRequest(RoleServiceUrlEnums.AllRoles_GET, 'get', REQUEST_SERVERS.fd_api_url, requestData)
  }

  getRolePermissions(id) {
    var requestData = { role_id: id, token: getObjectChildValue(JSON.parse(localStorage.getItem('data')), '', ['token']) }
    return this.requestService.sendRequest(RoleServiceUrlEnums.RolePermission_GET, 'get', REQUEST_SERVERS.fd_api_url, requestData)

  }
  submitPersmissions(requestData) {
	debugger;
    return this.requestService.sendRequest(RoleServiceUrlEnums.AttachPermission_Post, 'Post', REQUEST_SERVERS.fd_api_url, removeEmptyAndNullsFormObject(requestData))
  }
  getAutoGeneratedFolders() {
    return this.requestService.sendRequest(RoleServiceUrlEnums.AutoGeneratedFolders_Get, 'get', REQUEST_SERVERS.fd_api_url)
  }

  submitAttachFolderToRole(requestData) {
    return this.requestService.sendRequest(RoleServiceUrlEnums.AttachFolderTypeToRole, 'post', REQUEST_SERVERS.fd_api_url,requestData)
  }
  getRoleFolderType(formData){
    return this.requestService.sendRequest(RoleServiceUrlEnums.GetRoleFolderType_Get, 'get', REQUEST_SERVERS.fd_api_url,formData)
  }


}
