export enum RoleServiceUrlEnums {
    AllRoles_GET = 'roles_list',
    RolePermission_GET = 'permissions',
    AttachPermission_Post = "attach_permissions",
    AutoGeneratedFolders_Get="auto_generated_folders",
    AttachFolderTypeToRole='attach_folder_types_to_role',
    GetRoleFolderType_Get='get_role_folder_types'
}