export enum USERPERMISSIONS {
	add_case = "add-case",
	add_patient = "add-patient",
	appointment_filter = "appointment-filter",
	appointment_list_delete = "appointment-list-delete",
	basic_contact_edit = "basic-contact-edit",
	basic_contact_tab = "basic-contact-tab",
	billing_menu = "billing-menu",
	bulk_billing_billed_visit_add_task = "bulk-billing-billed-visit-add-task",
	bulk_billing_billed_visit_comment = "bulk-billing-billed-visit-comment",
	bulk_billing_billed_visit_delete = "bulk-billing-billed-visit-delete",
	bulk_billing_billed_visit_fax = "bulk-billing-billed-visit-fax",
	bulk_billing_billed_visit_filter = "bulk-billing-billed-visit-filter",
	bulk_billing_billed_visit_mail = "bulk-billing-billed-visit-mail",
	bulk_billing_billed_visit_print = "bulk-billing-billed-visit-print",
	bulk_billing_billed_visit_tab = "bulk-billing-billed-visit-tab",
	bulk_billing_billed_visit_view_bill = "bulk-billing-billed-visit-view-bill",
	bulk_billing_billed_visit_view_packet = "bulk-billing-billed-visit-view-packet",
	bulk_billing_billed_visit_zip = "bulk-billing-billed-visit-zip",
	bulk_billing_menu = "bulk-billing-menu",
	bulk_billing_packeted_add_task = "bulk-billing-packeted-add-task",
	bulk_billing_packeted_download = "bulk-billing-packeted-download",
	bulk_billing_packeted_fax = "bulk-billing-packeted-fax",
	bulk_billing_packeted_filter = "bulk-billing-packeted-filter",
	bulk_billing_packeted_generate_envelop = "bulk-billing-packeted-generate-envelop",
	bulk_billing_packeted_generate_pom = "bulk-billing-packeted-generate-pom",
	bulk_billing_packeted_mail = "bulk-billing-packeted-mail",
	bulk_billing_packeted_print = "bulk-billing-packeted-print",
	bulk_billing_packeted_tab = "bulk-billing-packeted-tab",
	bulk_billing_packeted_zip = "bulk-billing-packeted-zip",
	bulk_billing_pom_add_task = "bulk-billing-pom-add-task",
	bulk_billing_pom_commnet = "bulk-billing-pom-commnet",
	bulk_billing_pom_delete = "bulk-billing-pom-delete",
	bulk_billing_pom_filter = "bulk-billing-pom-filter",
	bulk_billing_pom_generate_envelop = "bulk-billing-pom-generate-envelop",
	bulk_billing_pom_generate_pom = "bulk-billing-pom-generate-pom",
	bulk_billing_pom_scan = "bulk-billing-pom-scan",
	bulk_billing_pom_tab = "bulk-billing-pom-tab",
	bulk_billing_pom_view = "bulk-billing-pom-view",
	bulk_billing_visit_desk_finalized_add_task = "bulk-billing-visit-desk-finalized-add-task",
	bulk_billing_visit_desk_finalized_comment = "bulk-billing-visit-desk-finalized-comment",
	bulk_billing_visit_desk_finalized_create_bill = "bulk-billing-visit-desk-finalized-create-bill",
	bulk_billing_visit_desk_finalized_delete = "bulk-billing-visit-desk-finalized-delete",
	bulk_billing_visit_desk_finalized_edit = "bulk-billing-visit-desk-finalized-edit",
	bulk_billing_visit_desk_finalized_fax = "bulk-billing-visit-desk-finalized-fax",
	bulk_billing_visit_desk_finalized_filter = "bulk-billing-visit-desk-finalized-filter",
	bulk_billing_visit_desk_finalized_mail = "bulk-billing-visit-desk-finalized-mail",
	bulk_billing_visit_desk_finalized_print = "bulk-billing-visit-desk-finalized-print",
	bulk_billing_visit_desk_finalized_tab = "bulk-billing-visit-desk-finalized-tab",
	bulk_billing_visit_desk_finalized_view_report = "bulk-billing-visit-desk-finalized-view-report",
	bulk_billing_visit_desk_menu = "bulk-billing-visit-desk-menu",
	bulk_billing_visit_desk_unfinalized_add_task = "bulk-billing-visit-desk-unfinalized-add-task",
	bulk_billing_visit_desk_unfinalized_comment = "bulk-billing-visit-desk-unfinalized-comment",
	bulk_billing_visit_desk_unfinalized_delete = "bulk-billing-visit-desk-unfinalized-delete",
	bulk_billing_visit_desk_unfinalized_edit = "bulk-billing-visit-desk-unfinalized-edit",
	bulk_billing_visit_desk_unfinalized_fax = "bulk-billing-visit-desk-unfinalized-fax",
	bulk_billing_visit_desk_unfinalized_mail = "bulk-billing-visit-desk-unfinalized-mail",
	bulk_billing_visit_desk_unfinalized_print = "bulk-billing-visit-desk-unfinalized-print",
	bulk_billing_visit_desk_unfinalized_tab = "bulk-billing-visit-desk-unfinalized-tab",

	adminBillingPomMenu="admin-billing-pom-menu",
	adminBillingPacketMenu="admin-billing-packet-menu",

	cancelled_appointment_add = "cancelled-appointment-add",
	cancelled_appointment_edit = "cancelled-appointment-edit",
	cancelled_appointment_filter = "cancelled-appointment-filter",
	case_info_tab = "case-info-tab",
	case_list_menu = "case-list-menu",
	case_listing = "case-listing",
	collection_menu = "collection-menu",
	create_case_task = "create-case-task",
	create_task_patient = "create-task-patient",
	customize_facility_color_create_task = "customize-facility-color-create-task",
	customize_facility_color_delete = "customize-facility-color-delete",
	customize_facility_color_filter = "scheduler-customize-facility-color-filter",
	delete_case = "delete-case",
	delete_patient = "delete-patient",
	doctor_calendar = "doctor-calendar",
	edit_case = "edit-case",
	edit_patient = "edit-patient",
	email_patient_summary = "email-patient-summary",
	emergency_contact_edit = "emergency-contact-edit",
	emergency_contact_tab = "emergency-contact-tab",
	export_patient_summary = "export-patient-summary",
	fax_patient_summary = "fax-patient-summary",
	filter_case = "filter-case",
	filter_patient = "filter-patient",
	form_filler_edit = "form-filler-edit",
	form_filler_tab = "form-filler-tab",
	gurantor_tab = "gurantor-tab",
	legal_guardian_tab = "legal-guardian-tab",
	master_groups_menu = "master-groups-menu",
	master_practice_create_task = "master-practice-create-task",
	master_speciality_create_task = "master-speciality-create-task",
	master_speciality_menu = "master-speciality-menu",
	master_user_department_create_task = "master-user-department-create-task",
	master_user_department_menu = "master-user-department-menu",
	master_user_designation_create_task = "master-user-designation-create-task",
	master_user_designation_menu = "master-user-designation-menu",
	master_user_emp_by_create_task = "master-user-emp-by-create-task",
	master_user_emp_by_menu = "master-user-emp-by-menu",
	master_user_emp_type_create_task = "master-user-emp-type-create-task",
	master_user_emp_type_menu = "master-user-emp-type-menu",
	master_user_list_create_task = "master-user-list-create-task",
	master_user_list_menu = "master-user-list-menu",
	master_user_roles_create_task = "master-user-roles-create-task",
	master_user_roles_menu = "master-user-roles-menu",
	my_tasks_add_task = "my-tasks-add-task",
	my_tasks_comment = "my-tasks-comment",
	my_tasks_delete = "my-tasks-delete",
	my_tasks_edit = "my-tasks-edit",
	my_tasks_filter = "my-tasks-filter",
	my_tasks_menu = "my-tasks-menu",
	my_tasks_view = "my-tasks-view",
	patient_accident_add_task = "patient-accident-add-task",
	patient_accident_delete = "patient-accident-delete",
	patient_accident_edit = "patient-accident-edit",
	patient_accident_tab = "patient-accident-tab",
	patient_attorney_info_edit = "patient-attorney-info-edit",
	patient_attorney_tab = "patient-attorney-tab",
	patient_authorization_tab = "patient-authorization-tab",
	patient_billing_billed_visit_add_task = "patient-billing-billed-visit-add-task",
	patient_billing_billed_visit_delete = "patient-billing-billed-visit-delete",
	patient_billing_billed_visit_download = "patient-billing-billed-visit-download",
	patient_billing_billed_visit_edit = "patient-billing-billed-visit-edit",
	patient_billing_billed_visit_fax = "patient-billing-billed-visit-fax",
	patient_billing_billed_visit_generate_envelop = "patient-billing-billed-visit-generate-envelop",
	patient_billing_billed_visit_generate_pom = "patient-billing-billed-visit-generate-pom",
	patient_billing_billed_visit_mail = "patient-billing-billed-visit-mail",
	patient_billing_billed_visit_tab = "patient-billing-billed-visit-tab",
	patient_billing_billed_visit_view_packet = "patient-billing-billed-visit-view-packet",
	patient_billing_packeted_create_task = "patient-billing-packeted-create-task",
	patient_billing_packeted_delete = "patient-billing-packeted-delete",
	patient_billing_packeted_download = "patient-billing-packeted-download",
	patient_billing_packeted_edit = "patient-billing-packeted-edit",
	patient_billing_packeted_fax = "patient-billing-packeted-fax",
	patient_billing_packeted_generate_envelop = "patient-billing-packeted-generate-envelop",
	patient_billing_packeted_generate_pom = "patient-billing-packeted-generate-pom",
	patient_billing_packeted_mail = "patient-billing-packeted-mail",
	patient_billing_packeted_print = "patient-billing-packeted-print",
	patient_billing_packeted_tab = "patient-billing-packeted-tab",
	patient_billing_packeted_view_packet = "patient-billing-packeted-view-packet",
	patient_billing_pom_add_task = "patient-billing-pom-add-task",
	patient_billing_pom_delete = "patient-billing-pom-delete",
	patient_billing_pom_print_envelop = "patient-billing-pom-print-envelop",
	patient_billing_pom_print_pom = "patient-billing-pom-print-pom",
	patient_billing_pom_tab = "patient-billing-pom-tab",
	patient_billing_menu = "patient-billing-menu",
	patient_billing_visit_desk_add_new_visit = "patient-billing-visit-desk-add-new-visit",
	patient_billing_visit_desk_create_bill = "patient-billing-visit-desk-create-bill",
	patient_billing_visit_desk_create_task = "patient-billing-visit-desk-create-task",
	patient_billing_visit_desk_delete = "patient-billing-visit-desk-delete",
	patient_billing_visit_desk_edit = "patient-billing-visit-desk-edit",
	patient_billing_visit_desk_fax = "patient-billing-visit-desk-fax",
	patient_billing_visit_desk_mail = "patient-billing-visit-desk-mail",
	patient_billing_visit_desk_view_doctor_report = "patient-billing-visit-desk-view-doctor-report",
	patient_billing_visit_tab = "patient-billing-visit-tab",
	patient_body_parts_add_task = "patient-body-parts-add-task",
	patient_body_parts_delete = "patient-body-parts-delete",
	patient_body_parts_edit = "patient-body-parts-edit",
	patient_body_parts_tab = "patient-body-parts-tab",
	patient_case_collection_menu = "patient-case-collection-menu",
	patient_case_comments_menu = "patient-case-comments-menu",
	patient_case_info_edit = "patient-case-info-edit",
	patient_case_marketing_menu = "patient-case-marketing-menu",
	patient_docs_add_task = "patient-docs-add-task",
	patient_docs_copy = "patient-docs-copy",
	patient_docs_create_folder = "patient-docs-create-folder",
	patient_docs_delete = "patient-docs-delete",
	patient_docs_download = "patient-docs-download",
	patient_docs_edit = "patient-docs-edit",
	patient_docs_fax = "patient-docs-fax",
	patient_docs_mail = "patient-docs-mail",
	patient_docs_menu = "patient-docs-menu",
	patient_docs_move = "patient-docs-move",
	patient_docs_print = "patient-docs-print",
	patient_docs_scan = "patient-docs-scan",
	patient_docs_search = "patient-docs-search",
	patient_docs_update_tags = "patient-docs-update-tags",
	patient_docs_upload = "patient-docs-upload",
	patient_docs_view = "patient-docs-view",
	patient_employer_add_employer = "patient-employer-add-employer",
	patient_employer_add_task = "patient-employer-add-task",
	patient_employer_delete = "patient-employer-delete",
	patient_employer_edit = "patient-employer-edit",
	patient_employer_tab = "patient-employer-tab",
	patient_gurantor_edit = "patient-gurantor-edit",
	patient_household_add_more_people = "patient-household-add-more-people",
	patient_household_add_task = "patient-household-add-task",
	patient_household_delete = "patient-household-delete",
	patient_household_edit = "patient-household-edit",
	patient_household_tab = "patient-household-tab",
	patient_injury_menu = "patient-injury-menu",
	patient_insurance_info_edit = "patient-insurance-info-edit",
	patient_insurance_menu = "patient-insurance-menu",
	patient_insurance_tab = "patient-insurance-tab",
	patient_legal_guardian_edit = "patient-legal-guardian-edit",
	patient_list_menu = "patient-list-menu",
	patient_listing = "patient-listing",
	patient_medical_treatment_add_task = "patient-medical-treatment-add-task",
	patient_medical_treatment_delete = "patient-medical-treatment-delete",
	patient_medical_treatment_edit = "patient-medical-treatment-edit",
	patient_medical_treatment_tab = "patient-medical-treatment-tab",
	patient_mri_intake_edit = "patient-mri-intake-edit",
	patient_mri_intake_tab = "patient-mri-intake-tab",
	patient_personal_info_edit = "patient-personal-info-edit",
	patient_profile = "patient-profile",
	patient_referrals_menu = "patient-referrals-menu",
	patient_schedular_menu = "patient-schedular-menu",
	patient_schedular_schedule_find_best = "patient-schedular-schedule-find-best",
	patient_schedular_schedule_history = "patient-schedular-schedule-history",
	patient_schedular_schedule_manual = "patient-schedular-schedule-manual",
	patient_schedular_schedule_tab = "patient-schedular-schedule-tab",
	patient_schedular_schedule_waiting_list = "patient-schedular-schedule-waiting-list",
	patient_summary = "patient-summary",
	patient_summary_menu = "patient-summary-menu",
	patient_vehicle_add_task = "patient-vehicle-add-task",
	patient_vehicle_delete = "patient-vehicle-delete",
	patient_vehicle_edit = "patient-vehicle-edit",
	patient_vehicle_tab = "patient-vehicle-tab",
	personal_information_menu = "personal-information-menu",
	personal_tab = "personal-tab",
	primary_care_physical_info_edit = "primary-care-physical-info-edit",
	referring_physical_info_edit = "referring-physical-info-edit",
	referring_physical_info_tab = "referring-physical-info-tab",
	reports_men = "reports-menu",
	room_add = "room-add",
	room_delete = "room-delete",
	room_menu = "room-menu",
	schedular_patient_list_add_task = "schedular-patient-list-add-task",
	schedular_patient_list_delete = "schedular-patient-list-delete",
	schedular_patient_list_edit = "schedular-patient-list-edit",
	schedular_patient_list_filter = "schedular-patient-list-filter",
	schedular_patient_list_tab = "schedular-patient-list-tab",
	schedular_patient_list_waiting_list = "schedular-patient-list-waiting-list",
	schedule_appointment = "schedule-appointment",
	schedule_list_add = "schedule-list-add",
	schedule_list_create_task = "schedule-list-create-task",
	schedule_list_edit = "schedule-list-edit",
	scheduled_appointment_list_delete = "scheduled-appointment-list-delete",
	tasks_menu = "tasks-menu",
	waiting_list_doctor_filter = "waiting-list-doctor-filter",
	waiting_list_edit = "waiting-list-edit",
	waiting_list_filter = "waiting-list-filter",
	settings_menu = "settings-menu",
	roles_and_permissions_setting = "roles-and-permissions-setting",
	setting_roles_and_permissions_update = "setting-roles-and-permissions-update",
	setting_roles_and_permissions_menu = "setting-roles-and-permissions-menu",
	setting_roles_and_permissions_view = "setting-roles-and-permissions-view",
	setting_facility_menu = "setting-facility-menu",
	setting_facility_view = "setting-facility-view",
	setting_facility_update = "setting-facility-update",
	change_practice_setting = "change-practice-setting",
	customize_speciality_timeslot_edit = "customize-speciality-timeslot-edit",
	customize_speciality_overbooking_edit = "customize-speciality-overbooking-edit",
	customize_speciality_filter = "scheduler-customize-speciality-color-filter",
	//Reports
	reports_menu = "reports-menu",
	reports_menu_nf2 = "reports-menu-nf2",
	// Master
	master_menu = 'master-menu',
	// Provider
	master_provider_menu = 'master-provider-menu',
	// Specialty
	master_speciality_tab = 'master-speciality-tab',
	master_speciality_view = 'master-speciality-view',
	master_speciality_add_new = 'master-speciality-add-new',
	master_speciality_filter = 'master-speciality-filter',
	master_speciality_edit = 'master-speciality-edit',
	master_speciality_delete = 'master-speciality-delete',
	// Case Type
	master_case_type_tab = 'master-case-type-tab',
	master_case_type_view = 'master-case-type-view',
	master_case_type_add_new = 'master-case-type-add-new',
	master_case_type_filter = 'master-case-type-filter',
	master_case_type_edit = 'master-case-type-edit',
	master_case_type_delete = 'master-case-type-delete',
	// Visit Type
	master_visit_type_tab = 'master-visit-type-tab',
	master_visit_type_view = 'master-visit-type-view',
	master_visit_type_add_new = 'master-visit-type-add-new',
	master_visit_type_filter = 'master-visit-type-filter',
	master_visit_type_edit = 'master-visit-type-edit',
	master_visit_type_delete = 'master-visit-type-delete',
	// Practice
	master_practice_menu = 'master-practice-menu',
	// Practice
	master_practice_tab = 'master-practice-tab',
	master_practice_view = 'master-practice-view',
	master_practice_add_new = 'master-practice-add-new',
	master_practice_edit = 'master-practice-edit',
	master_practice_delete = 'master-practice-delete',
	master_practice_filter = 'master-practice-filter',
	master_practice_add_location = 'master-practice-add-location',
	master_practice_edit_location = 'master-practice-edit-location',
	master_practice_delete_location = 'master-practice-delete-location',
	master_practice_location_view = 'master-practice-location-view',
	// Hospital
	master_hospital_tab = 'master-hospital-tab',
	master_hospital_view = 'master-hospital-view',
	master_hospital_add_new = 'master-hospital-add-new',
	master_hospital_filter = 'master-hospital-filter',
	master_hospital_edit = 'master-hospital-edit',
	master_hospital_delete = 'master-hospital-delete',
	// Referring Physician
	master_practice_referring_physician_menu = 'master-practice-referring-physician-menu',
	// Clinic
	master_clinic_tab = 'master-clinic-tab',
	master_clinic_view = 'master-clinic-view',
	master_clinic_add_new = 'master-clinic-add-new',
	master_clinic_edit = 'master-clinic-edit',
	master_clinic_delete = 'master-clinic-delete',
	// Referring Physician
	master_referring_physician_tab = 'master-referring-physician-tab',
	master_referring_physician_view = 'master-referring-physician-view',
	master_referring_physician_add_new = 'master-referring-physician-add-new',
	master_referring_physician_edit = 'master-referring-physician-edit',
	master_referring_physician_delete = 'master-referring-physician-delete',
	// User
	master_user_menu = 'master-user-menu',
	// User
	master_user_list_tab = 'master-user-list-tab',
	master_user_list_view = 'master-user-list-view',
	master_user_list_add = 'master-user-list-add',
	master_user_list_filter = 'master-user-list-filter',
	master_user_list_edit = 'master-user-list-edit',
	master_user_list_delete = 'master-user-list-delete',
	master_user_list_edit_email = 'master-user-list-edit-email',
	master_user_list_edit_status = 'master-user-list-edit-status',
	// User Roles
	master_user_roles_tab = 'master-user-roles-tab',
	master_user_roles_view = 'master-user-roles-view',
	master_user_roles_add = 'master-user-roles-add',
	master_user_roles_filter = 'master-user-roles-filter',
	master_user_roles_edit = 'master-user-roles-edit',
	master_user_roles_delete = 'master-user-roles-delete',
	// ID Proofing
	master_idProofing_tab = 'master-idProofing-tab',
	// Group
	master_groups_tab = 'master-groups-tab',
	master_groups_view = 'master-groups-view',
	master_groups_add = 'master-groups-add',
	master_groups_filter = 'master-groups-filter',
	master_groups_edit = 'master-groups-edit',
	master_groups_delete = 'master-groups-delete',
	// Designation
	master_user_designation_tab = 'master-user-designation-tab',
	master_user_designation_view = 'master-user-designation-view',
	master_user_designation_add = 'master-user-designation-add',
	master_user_designation_filter = 'master-user-designation-filter',
	master_user_designation_edit = 'master-user-designation-edit',
	master_user_designation_delete = 'master-user-designation-delete',
	// Department
	master_user_department_tab = 'master-user-department-tab',
	master_user_department_view = 'master-user-department-view',
	master_user_department_add = 'master-user-department-add',
	master_user_department_filter = 'master-user-department-filter',
	master_user_department_edit = 'master-user-department-edit',
	master_user_department_delete = 'master-user-department-delete',
	// Employment Type
	master_user_emp_type_tab = 'master-user-emp-type-tab',
	master_user_emp_type_add = 'master-user-emp-type-add',
	master_user_emp_type_filter = 'master-user-emp-type-filter',
	master_user_emp_type_edit = 'master-user-emp-type-edit',
	master_user_emp_type_view = 'master-user-emp-type-view',
	master_user_emp_type_delete = 'master-user-emp-type-delete',
	// Employment By
	master_user_emp_by_tab = 'master-user-emp-by-tab',
	master_user_emp_by_view = 'master-user-emp-by-view',
	master_user_emp_by_add = 'master-user-emp-by-add',
	master_user_emp_by_filter = 'master-user-emp-by-filter',
	master_user_emp_by_edit = 'master-user-emp-by-edit',
	master_user_emp_by_delete = 'master-user-emp-by-delete',
	// Scheduler
	master_schedular_menu = 'master-schedular-menu',
	// Billing
	master_billing_menu = 'master-billing-menu',
	// Invoice
	master_invoice_menu = 'master-invoice-menu',
	//inventory
	master_inventory_fields_tab = "master-inventory-fields-tab",  
	master_inventory_fields_view = "master-inventory-fields-view",  
	master_inventory_fields_filter = "master-inventory-fields-filter",  
	master_inventory_fields_add = "master-inventory-fields-add",  
	master_inventory_fields_edit = "master-inventory-fields-edit",  
	master_inventory_fields_delete = "master-inventory-fields-delete",  
	//shipping
	master_shipping_fields_tab = "master-shipping-fields-tab",  
	master_shipping_fields_view = "master-shipping-fields-view",  
	master_shipping_fields_filter = "master-shipping-fields-filter",  
	master_shipping_fields_add = "master-shipping-fields-add",  
	master_shipping_fields_edit = "master-shipping-fields-edit",  
	master_shipping_fields_delete = "master-shipping-fields-delete",
	//tax
	master_tax_fields_tab = "master-tax-fields-tab",  
	master_tax_fields_view = "master-tax-fields-view",  
	master_tax_fields_filter = "master-tax-fields-filter",  
	master_tax_fields_add = "master-tax-fields-add",  
	master_tax_fields_edit = "master-tax-fields-edit",  
	master_tax_fields_delete = "master-tax-fields-delete",
	//invoice
	master_invoice_fields_tab = "master-invoice-fields-tab",  
	master_invoice_fields_view = "master-invoice-fields-view",  
	master_invoice_fields_filter = "master-invoice-fields-filter",  
	master_invoice_fields_add = "master-invoice-fields-add",  
	master_invoice_fields_edit = "master-invoice-fields-edit",  
	master_invoice_fields_delete = "master-invoice-fields-delete",
	// Insurance
	master_billing_insurance_menu = 'master-billing-insurance-menu',
	// Insurance
	master_billing_insurance_tab = 'master-billing-insurance-tab',
	master_billing_insurance_view = 'master-billing-insurance-view',
	master_billing_insurance_add = 'master-billing-insurance-add',
	master_billing_insurance_filter = 'master-billing-insurance-filter',
	master_billing_insurance_edit = 'master-billing-insurance-edit',
	master_billing_insurance_delete = 'master-billing-insurance-delete',

	// new Permission 
	master_billing_insurance_location_edit = 'master-billing-insurance-location-edit',
	master_billing_insurance_location_add = 'master-billing-insurance-location-add',

	// Adjuster Information
	master_billing_adjuster_tab = 'master-billing-adjuster-tab',
	master_billing_adjuster_view = 'master-billing-adjuster-view',
	master_billing_adjuster_add = 'master-billing-adjuster-add',
	master_billing_adjuster_filter = 'master-billing-adjuster-filter',
	master_billing_adjuster_edit = 'master-billing-adjuster-edit',
	master_billing_adjuster_delete = 'master-billing-adjuster-delete',
	// Plan Name
	master_billing_plan_name_tab = 'master-billing-plan-name-tab',
	master_billing_plan_name_view = 'master-billing-plan-name-view',
	master_billing_plan_name_add = 'master-billing-plan-name-add',
	master_billing_plan_name_filter = 'master-billing-plan-name-filter',
	master_billing_plan_name_edit = 'master-billing-plan-name-edit',
	master_billing_plan_name_delete = 'master-billing-plan-name-delete',
	// Plan Type
	master_billing_plan_type_tab = 'master-billing-plan-type-tab',
	master_billing_plan_type_view = 'master-billing-plan-type-view',
	master_billing_plan_type_add = 'master-billing-plan-type-add',
	master_billing_plan_type_filter = 'master-billing-plan-type-filter',
	master_billing_plan_type_edit = 'master-billing-plan-type-edit',
	master_billing_plan_type_delete = 'master-billing-plan-type-delete',
	// Attorney
	master_billing_attorney_menu = 'master-billing-attorney-menu',
	// Firm
	master_billing_firm_tab = 'master-billing-firm-tab',
	master_billing_firm_view = 'master-billing-firm-view',
	master_billing_firm_add = 'master-billing-firm-add',
	master_billing_firm_filter = 'master-billing-firm-filter',
	master_billing_firm_edit = 'master-billing-firm-edit',
	master_billing_firm_delete = 'master-billing-firm-delete',

	// new Permission
	master_billing_firm_location_add = "master-billing-firm-location-add",
	master_billing_firm_location_edit = "master-billing-firm-location-edit",

	// Attorney
	master_billing_attorney_tab = 'master-billing-attorney-tab',
	master_billing_attorney_view = 'master-billing-attorney-view',
	master_billing_attorney_add = 'master-billing-attorney-add',
	master_billing_attorney_filter = 'master-billing-attorney-filter',
	master_billing_attorney_edit = 'master-billing-attorney-edit',
	master_billing_attorney_delete = 'master-billing-attorney-delete',
	// Employer
	master_billing_employer_menu = 'master-billing-employer-menu',
	master_billing_employer_view = 'master-billing-employer-view',
	master_billing_employer_add = 'master-billing-employer-add',
	master_billing_employer_filter = 'master-billing-employer-filter',
	master_billing_employer_edit = 'master-billing-employer-edit',
	master_billing_employer_delete = 'master-billing-employer-delete',
	// Clearinghouse
	master_clearinghouse_menu = 'master-clearinghouse-menu',
	master_clearinghouse_view = 'master-clearinghouse-view',
	master_clearinghouse_add = 'master-clearinghouse-add',
	master_clearinghouse_filter = 'master-clearinghouse-filter',
	master_clearinghouse_edit = 'master-clearinghouse-edit',
	master_clearinghouse_delete = 'master-clearinghouse-delete',
	// Employer-Insurance Linkage
	master_employer_insurance_linkage_menu = 'master-employer-insurance-linkage-menu',
	master_employer_insurance_linkage_view = 'master-employer-insurance-linkage-view',
	master_employer_insurance_linkage_add = 'master-employer-insurance-linkage-add',
	master_employer_insurance_linkage_filter = 'master-employer-insurance-linkage-filter',
	master_employer_insurance_linkage_edit = 'master-employer-insurance-linkage-edit',
	master_employer_insurance_linkage_delete = 'master-employer-insurance-linkage-delete',
	// Codes
	master_billing_codes_menu = 'master-billing-codes-menu',
	// ICT-10 Codes
	master_billing_codes_icd_tab = 'master-billing-codes-icd-tab',
	master_billing_codes_icd_view = 'master-billing-codes-icd-view',
	master_billing_codes_icd_add = 'master-billing-codes-icd-add',
	master_billing_codes_icd_filter = 'master-billing-codes-icd-filter',
	master_billing_codes_icd_edit = 'master-billing-codes-icd-edit',
	master_billing_codes_icd_delete = 'master-billing-codes-icd-delete',
	// CPT Codes
	master_billing_codes_cpt_tab = 'master-billing-codes-cpt-tab',
	master_billing_codes_cpt_view = 'master-billing-codes-cpt-view',
	master_billing_codes_cpt_add = 'master-billing-codes-cpt-add',
	master_billing_codes_cpt_filter = 'master-billing-codes-cpt-filter',
	master_billing_codes_cpt_edit = 'master-billing-codes-cpt-edit',
	master_billing_codes_cpt_delete = 'master-billing-codes-cpt-delete',
	// HCPCS
	master_billing_codes_hcpcs_tab = 'master-billing-codes-hcpcs-tab',
	master_billing_codes_hcpcs_view = 'master-billing-codes-hcpcs-view',
	master_billing_codes_hcpcs_add = 'master-billing-codes-hcpcs-add',
	master_billing_codes_hcpcs_filter = 'master-billing-codes-hcpcs-filter',
	master_billing_codes_hcpcs_edit = 'master-billing-codes-hcpcs-edit',
	master_billing_codes_hcpcs_delete = 'master-billing-codes-hcpcs-delete',
	// Fee Schedule
	master_billing_codes_fee_sc_tab = 'master-billing-codes-fee-sc-tab',
	master_billing_codes_fee_sc_view = 'master-billing-codes-fee-sc-view',
	master_billing_codes_fee_sc_add = 'master-billing-codes-fee-sc-add',
	master_billing_codes_fee_sc_filter = 'master-billing-codes-fee-sc-filter',
	master_billing_codes_fee_sc_edit = 'master-billing-codes-fee-sc-edit',
	master_billing_codes_fee_sc_delete = 'master-billing-codes-fee-sc-delete',
	//Fee Type

	master_billing_codes_fee_type_tab = 'master-billing-codes-fee-type-tab',
	master_billing_codes_fee_type_view = 'master-billing-codes-fee-type-view',
	master_billing_codes_fee_type_filter = 'master-billing-codes-fee-type-filter',
	master_billing_codes_fee_type_add = 'master-billing-codes-fee-type-add',
	master_billing_codes_fee_type_view_single = 'master-billing-codes-fee-type-view-single',
	master_billing_codes_fee_type_edit = 'master-billing-codes-fee-type-edit',
	master_billing_codes_fee_type__delete = 'master-billing-codes-fee-type-delete',

	//Code Type

	master_billing_codes_code_type_tab = 'master-billing-codes-code-type-tab',
	master_billing_codes_code_type_view = 'master-billing-codes-code-type-view',
	master_billing_codes_code_type_filter = 'master-billing-codes-code-type-filter',
	master_billing_codes_code_type_add = 'master-billing-codes-code-type-add',
	master_billing_codes_code_type_view_single = 'master-billing-codes-code-type-view-single',
	master_billing_codes_code_type_edit = 'master-billing-codes-code-type-edit',

	// Billing
	master_billing_billing_menu = 'master-billing-billing-menu',
	// Payment Type
	master_bb_pt_tab = 'master-bb-pt-tab',
	master_bb_pt_view = 'master-bb-pt-view',
	master_bb_pt_add = 'master-bb-pt-add',
	master_bb_pt_filter = 'master-bb-pt-filter',
	master_bb_pt_edit = 'master-bb-pt-edit',
	master_bb_pt_delete = 'master-bb-pt-delete',
	// Verification Type
	master_bb_vt_tab = 'master-bb-vt-tab',
	master_bb_vt_view = 'master-bb-vt-view',
	master_bb_vt_add = 'master-bb-vt-add',
	master_bb_vt_filter = 'master-bb-vt-filter',
	master_bb_vt_edit = 'master-bb-vt-edit',
	master_bb_vt_delete = 'master-bb-vt-delete',
	// Denial
	master_bb_denial_tab = 'master-bb-denial-tab',
	master_bb_denial_view = 'master-bb-denial-view',
	master_bb_denial_add = 'master-bb-denial-add',
	master_bb_denial_filter = 'master-bb-denial-filter',
	master_bb_denial_edit = 'master-bb-denial-edit',
	master_bb_denial_delete = 'master-bb-denial-delete',
	// Paid By
	master_bb_pb_tab = 'master-bb-pb-tab',
	master_bb_pb_view = 'master-bb-pb-view',
	master_bb_pb_add = 'master-bb-pb-add',
	master_bb_pb_filter = 'master-bb-pb-filter',
	master_bb_pb_edit = 'master-bb-pb-edit',
	master_bb_pb_delete = 'master-bb-pb-delete',
	// Place Of Service
	master_bb_pos_tab = 'master-bb-pos-tab',
	master_bb_pos_view = 'master-bb-pos-view',
	master_bb_pos_add = 'master-bb-pos-add',
	master_bb_pos_filter = 'master-bb-pos-filter',
	master_bb_pos_edit = 'master-bb-pos-edit',
	master_bb_pos_delete = 'master-bb-pos-delete',
	// Modifiers
	master_bb_mod_tab = 'master-bb-mod-tab',
	master_bb_mod_view = 'master-bb-mod-view',
	master_bb_mod_add = 'master-bb-mod-add',
	master_bb_mod_filter = 'master-bb-mod-filter',
	master_bb_mod_edit = 'master-bb-mod-edit',
	master_bb_mod_delete = 'master-bb-mod-delete',
	// Case Status
	master_bb_cs_tab = 'master-bb-cs-tab',
	master_bb_cs_view = 'master-bb-cs-view',
	master_bb_cs_add = 'master-bb-cs-add',
	master_bb_cs_filter = 'master-bb-cs-filter',
	master_bb_cs_edit = 'master-bb-cs-edit',
	master_bb_cs_delete = 'master-bb-cs-delete',
	// Region
	master_bb_region_tab = 'master-bb-region-tab',
	master_bb_region_view = 'master-bb-region-view',
	master_bb_region_add = 'master-bb-region-add',
	master_bb_region_filter = 'master-bb-region-filter',
	master_bb_region_edit = 'master-bb-region-edit',
	master_bb_region_delete = 'master-bb-region-delete',
	// Billing Employment Type
	master_bb_emp_type_tab = 'master-bb-emp-type-tab',
	master_bb_emp_type_view = 'master-bb-emp-type-view',
	master_bb_emp_type_add = 'master-bb-emp-type-add',
	master_bb_emp_type_filter = 'master-bb-emp-type-filter',
	master_bb_emp_type_edit = 'master-bb-emp-type-edit',
	master_bb_emp_type_delete = 'master-bb-emp-type-delete',
	// Billing Title
	master_bb_billing_title_tab = 'master-bb-billing-title-tab',
	master_bb_billing_title_view = 'master-bb-billing-title-view',
	master_bb_billing_title_add = 'master-bb-billing-title-add',
	master_bb_billing_title_filter = 'master-bb-billing-title-filter',
	master_bb_billing_title_edit = 'master-bb-billing-title-edit',
	master_bb_billing_title_delete = 'master-bb-billing-title-delete',

	// Bill Status 
	master_bb_bill_status_view = "master-bb-bill-status-view",
	// Template
	master_template_menu = 'master-template-menu',
	// Required fileds/Controls
	master_template_fileds_tab = 'master-template-fileds-tab',
	master_template_fileds_view = 'master-template-fileds-view',
	master_template_fileds_filter = 'master-template-fileds-filter',
	// Roles & Fields
	master_template_roles_fields_tab = 'master-template-roles-fields-tab',
	master_template_roles_fields_view = 'master-template-roles-fields-view',
	master_template_roles_fields_add = 'master-template-roles-fields-add',
	master_template_roles_fields_filter = 'master-template-roles-fields-filter',
	master_template_roles_fields_edit = 'master-template-roles-fields-edit',
	// Erx
	master_erx_menu = 'master-erx-menu',
	// Erx List
	master_erx_tab = 'master-erx-tab',
	// Patient
	patient_menu = "patient-menu",
	// Patient List
	patient_patient_list_menu = "patient-patient-list-menu",
	patient_patient_list_add = "patient-patient-list-add",
	patient_patient_list_filter = "patient-patient-list-filter",
	patient_patient_list_listing = "patient-patient-list-listing",
	patient_patient_list_edit = "patient-patient-list-edit",
	patient_patient_list_profile = "patient-patient-list-profile",
	patient_patient_list_delete = "patient-patient-list-delete",
	// Case List
	patient_case_list_menu = "patient-case-list-menu",
	patient_case_list_add = "patient-case-list-add",
	patient_case_list_filter = "patient-case-list-filter",
	patient_case_list_listing = "patient-case-list-listing",
	patient_case_list_delete = "patient-case-list-delete",
	// Edit Case
	patient_case_list_edit_case = "patient-case-list-edit-case",
	// Patient Summary
	patient_case_list_patient_summary_menu = "patient-case-list-patient-summary-menu",
	patient_case_list_patient_summary = "patient-case-list-patient-summary",
	patient_case_list_patient_summary_export = "patient-case-list-patient-summary-export",
	patient_case_list_patient_summary_email = "patient-case-list-patient-summary-email",
	patient_case_list_patient_summary_fax = "patient-case-list-patient-summary-fax",
	// Personal Information
	patient_case_list_personal_information_menu = "patient-case-list-personal-information-menu",
	// Personal
	patient_case_list_personal_information_personal_tab = "patient-case-list-personal-information-personal-tab",
	patient_case_list_personal_information_personal_view = "patient-case-list-personal-information-personal-view",
	patient_case_list_personal_information_personal_edit = "patient-case-list-personal-information-personal-edit",
	// Basic Contact
	patient_case_list_personal_information_basic_contact_tab = "patient-case-list-personal-information-basic-contact-tab",
	patient_case_list_personal_information_basic_contact_view = "patient-case-list-personal-information-basic-contact-view",
	patient_case_list_personal_information_basic_contact_edit = "patient-case-list-personal-information-basic-contact-edit",
	// Emergency Contact
	patient_case_list_personal_information_emergency_contact_tab = "patient-case-list-personal-information-emergency-contact-tab",
	patient_case_list_personal_information_emergency_contact_view = "patient-case-list-personal-information-emergency-contact-view",
	patient_case_list_personal_information_emergency_contact_edit = "patient-case-list-personal-information-emergency-contact-edit",
	// Form Filler
	patient_case_list_personal_information_form_filler_tab = "patient-case-list-personal-information-form-filler-tab",
	patient_case_list_personal_information_form_filler_view = "patient-case-list-personal-information-form-filler-view",
	patient_case_list_personal_information_form_filler_edit = "patient-case-list-personal-information-form-filler-edit",
	// Legal Guardian
	patient_case_list_personal_information_legal_guardian_tab = "patient-case-list-personal-information-legal-guardian-tab",
	patient_case_list_personal_information_legal_guardian_view = "patient-case-list-personal-information-legal-guardian-view",
	patient_case_list_personal_information_legal_guardian_edit = "patient-case-list-personal-information-legal-guardian-edit",
	// Gurantor
	patient_case_list_personal_information_gurantor_tab = "patient-case-list-personal-information-gurantor-tab",
	patient_case_list_personal_information_gurantor_view = "patient-case-list-personal-information-gurantor-view",
	patient_case_list_personal_information_gurantor_edit = "patient-case-list-personal-information-gurantor-edit",
	// Case Info
	patient_case_list_case_info_menu = "patient-case-list-case-info-menu",
	patient_case_list_case_info_view = "patient-case-list-case-info-view",
	patient_case_list_case_info_edit = "patient-case-list-case-info-edit",
	// Insurance
	patient_case_list_insurance_menu = "patient-case-list-insurance-menu",
	// Attorney
	patient_case_list_insurance_attorney_tab = "patient-case-list-insurance-attorney-tab",
	patient_case_list_insurance_attorney_info_view = "patient-case-list-insurance-attorney-info-view",
	patient_case_list_insurance_attorney_info_edit = "patient-case-list-insurance-attorney-info-edit",
	// Insurance
	patient_case_list_insurance_insurance_tab = "patient-case-list-insurance-insurance-tab",
	patient_case_list_insurance_insurance_info_view = "patient-case-list-insurance-insurance-info-view",
	patient_case_list_insurance_insurance_info_edit = "patient-case-list-insurance-insurance-info-edit",
	// Employer
	patient_case_list_insurance_employer_tab = "patient-case-list-insurance-employer-tab",
	patient_case_list_insurance_employer_view = "patient-case-list-insurance-employer-view",
	patient_case_list_insurance_employer_edit = "patient-case-list-insurance-employer-edit",
	patient_case_list_insurance_employer_delete = "patient-case-list-insurance-employer-delete",
	// Accident
	patient_case_list_insurance_accident_tab = "patient-case-list-insurance-accident-tab",
	patient_case_list_insurance_accident_view = "patient-case-list-insurance-accident-view",
	patient_case_list_insurance_accident_edit = "patient-case-list-insurance-accident-edit",
	patient_case_list_insurance_accident_delete = "patient-case-list-insurance-accident-delete",
	// Vehicle
	patient_case_list_insurance_vehicle_tab = "patient-case-list-insurance-vehicle-tab",
	patient_case_list_insurance_vehicle_view = "patient-case-list-insurance-vehicle-view",
	patient_case_list_insurance_vehicle_edit = "patient-case-list-insurance-vehicle-edit",
	// Household Information
	patient_case_list_insurance_household_tab = "patient-case-list-insurance-household-tab",
	patient_case_list_insurance_household_view = "patient-case-list-insurance-household-view",
	patient_case_list_insurance_household_edit = "patient-case-list-insurance-household-edit",
	patient_case_list_insurance_household_delete = "patient-case-list-insurance-household-delete",
	// Medical Treatment
	patient_case_list_insurance_medical_treatment_tab = "patient-case-list-insurance-medical-treatment-tab",
	patient_case_list_insurance_medical_treatment_view = "patient-case-list-insurance-medical-treatment-view",
	patient_case_list_insurance_medical_treatment_edit = "patient-case-list-insurance-medical-treatment-edit",
	patient_case_list_insurance_medical_treatment_delete = "patient-case-list-insurance-medical-treatment-delete",

	patient_case_list_insurance_mri_intake_tab = "no-permission",
	// patient_case_list_insurance_medical_treatment_view = "patient-case-list-insurance-medical-treatment-view",
	// patient_case_list_insurance_medical_treatment_edit = "patient-case-list-insurance-medical-treatment-edit",
	// patient_case_list_insurance_medical_treatment_delete = "patient-case-list-insurance-medical-treatment-delete",
	// Injury
	patient_case_list_injury_menu = "patient-case-list-injury-menu",
	// Body Parts
	patient_case_list_injury_body_parts_tab = "patient-case-list-injury-body-parts-tab",
	patient_case_list_injury_body_parts_view = "patient-case-list-injury-body-parts-view",
	patient_case_list_injury_body_parts_edit = "patient-case-list-injury-body-parts-edit",
	patient_case_list_injury_body_parts_delete = "patient-case-list-injury-body-parts-delete",
	// Referrals
	patient_case_list_referrals_menu = "patient-case-list-referrals-menu",
	// Physician Information
	patient_case_list_referrals_physical_information_tab = "patient-case-list-referrals-physical-information-tab",
	patient_case_list_referrals_physical_information_view = "patient-case-list-referrals-physical-information-view",
	patient_case_list_referrals_physical_information_edit = "patient-case-list-referrals-physical-information-edit",
	// Marketing
	patient_case_list_marketing_menu = "patient-case-list-marketing-menu",
	patient_case_marketing_view = "patient-case-marketing-view",
	patient_case_marketing_edit = "patient-case-marketing-edit",
	// Documents
	patient_case_list_docs_menu = "patient-case-list-docs-menu",
	patient_case_list_docs_upload = "patient-case-list-docs-upload",
	patient_case_list_docs_merge = "patient-case-list-docs-merge",
	patient_case_list_docs_push_to_kiosk = "patient-case-list-docs-push-to-kiosk",
	patient_case_list_docs_scan = "patient-case-list-docs-scan",
	patient_case_list_docs_download = "patient-case-list-docs-download",
	patient_case_list_docs_print = "patient-case-list-docs-print",
	patient_case_list_docs_mail = "patient-case-list-docs-mail",
	patient_case_list_docs_fax = "patient-case-list-docs-fax",
	patient_case_list_docs_edit = "patient-case-list-docs-edit",
	patient_case_list_docs_delete = "patient-case-list-docs-delete",
	patient_case_list_docs_move = "patient-case-list-docs-move",
	patient_case_list_docs_copy = "patient-case-list-docs-copy",
	patient_case_list_docs_view = "patient-case-list-docs-view",
	patient_case_list_docs_update_tags = "patient-case-list-docs-update-tags",
	patient_case_list_docs_search = "patient-case-list-docs-search",
	patient_case_list_docs_create_folder = "patient-case-list-docs-create-folder",
	// Scheduler
	patient_case_list_scheduler_menu = "patient-case-list-scheduler-menu",
	patient_case_list_scheduler_view = "patient-case-list-scheduler-view",
	patient_case_list_scheduler_appointment_list_tab = "patient-case-list-scheduler-appointment-list",
	// Scheduler
	patient_case_list_Scheduler_scheduler_tab = "patient-case-list-Scheduler-scheduler-tab",
	patient_case_list_Scheduler_scheduler_view = "patient-case-list-Scheduler-scheduler-view",
	patient_case_list_Scheduler_scheduler_find_best = "patient-case-list-Scheduler-scheduler-find-best",
	patient_case_list_Scheduler_scheduler_manual = "patient-case-list-Scheduler-scheduler-manual",
	patient_case_list_Scheduler_scheduler_add_to_waiting_list = "patient-case-list-Scheduler-scheduler-add-to-waiting-list",
	patient_case_list_Scheduler_scheduler_schedule_history = "patient-case-list-Scheduler-scheduler-schedule-history",
	//visit
	patient_case_list_visits_menu = "patient-case-list-visits-menu",
	patient_case_list_visits_view = "patient-case-list-visits-view",
	patient_case_list_visits_specialty_filters = "patient-case-list-visits-specialty-filters",
	patient_case_list_visits_list_filters = "patient-case-list-visits-list-filters",
	patient_case_list_visits_pdfs_view = "patient-case-list-visits-pdfs-view",
	patient_case_list_visits_create_bill = "patient-case-list-visits-create-bill",
	patient_case_list_visits_edit_visit = "patient-case-list-visits-edit-visit",
	patient_case_list_visits_edit_visit_view = "patient-case-list-visits-edit-visit-view",
	patient_case_list_visits_edit_visit_upload_documents = "patient-case-list-visits-edit-visit-upload-documents",
	//Billing
	patient_case_list_billing_menu = "patient-case-list-billing-menu",
	patient_case_list_billing_view = "patient-case-list-billing-view",
	patient_case_list_billing_edit_bill = "patient-case-list-billing-edit-bill",
	patient_case_list_billing_pdfs_view = "patient-case-list-billing-pdfs-view",
	patient_case_list_billing_view_comments = "patient-case-list-billing-view-comments",
	patient_case_list_billing_view_bill_details = "patient-case-list-billing-view-bill-details",
	patient_case_list_comments_menu = "patient-case-list-comments-menu",
	patient_case_list_comments_view = "patient-case-list-comments-view",
	patient_case_list_comments_user_filters = "patient-case-list-comments-user-filters",
	patient_case_list_comments_add = "patient-case-list-comments-add",


	// Scheduler
	scheduler_menu = "scheduler-menu",
	appointment_add = "scheduler-create-appointment",
	appointment_edit = "scheduler-edit-appointment",
	appointment_delete = "scheduler-delete-appointment",
	all_doctors = "schedule-doctor-provider-access",
	all_specialty_access="schedule-doctor-specialty-access",
	add_previous_appointment = "scheduler-add-previous-appointment",
	update_previous_appointment = "scheduler-update-previous-appointment",
	// Scheduler List
	scheduler_list_menu = "scheduler-list-menu",
	schedule_list_view = "schedule-list-view",
	schedule_list_delete = "schedule-list-delete-appointment",
	schedule_list_filter = "schedule-list-filter",
	// Appointment List
	appointment_list_menu = "schedule-appointment-list-menu",
	schedule_appointment_list_view = "schedule-appointment-list-view",
	waiting_list_add = "schedule-waiting-list-add",
	schedule_appointment_list_filter = "schedule-appointment-list-filter",
	// Doctor Calender
	doctor_calendar_menu = "schedule-doctor-calendar-menu",
	schedule_doctor_calendar_view = "schedule-doctor-calendar-view",

	start_evaluation = "schedule-doctor-start-evaluation",
	// Access Note
	note = "schedule-doctor-access-note-view",
	schedule_doctor_access_note_view = "schedule-doctor-access-note-view",
	note_add = "schedule-doctor-access-note-add",
	// Unavailability
	schedule_doctor_unavailability_tab = "schedule-doctor-unavailability-tab",
	schedule_doctor_unavailability_view = "schedule-doctor-unavailability-view",
	unavailability_add = "schedule-doctor-unavailability-add",
	unavailablity_delete = "schedule-doctor-unavailability-delete",
	// Waiting list For Front Desk
	waiting_list_menu = "schedule-waiting-list-front-desk-menu",
	schedule_waiting_list_front_desk_view = "schedule-waiting-list-front-desk-view",
	waiting_list_delete = "schedule-waiting-list-front-desk-entry-delete",
	schedule_waiting_list_front_desk_filter = "schedule-waiting-list-front-desk-filter",
	// Cancelled Appointment List
	cancelled_appointment_menu = "schedule-cancelled-appointment-list-menu",
	schedule_cancelled_appointment_list_view = "schedule-cancelled-appointment-list-view",
	cancelled_appointment_delete = "schedule-cancelled-appointment-list-delete",
	cancelled_appointment_list_undo="schedule-cancelled-appointment-list-undo",
	schedule_cancelled_appointment_list_filter = "schedule-cancelled-appointment-list-filter",
	// Customize
	scheduler_customize_menu = "scheduler-customize-menu",
	// Practice
	customize_facility_menu = "scheduler-customize-facility-menu",
	scheduler_customize_facility_color_view = "scheduler-customize-facility-color-view",
	customize_facility_color_edit = "scheduler-customize-facility-color-edit",
	// customize_facility_color_filter = "cheduler-customize-facility-color-filter",
	// Specialty
	customize_speciality_menu = "scheduler-customize-speciality-menu",
	scheduler_customize_speciality_color_view = "scheduler-customize-speciality-color-view",
	customize_speciality_color_edit = "scheduler-customize-speciality-color-edit",
	// Preferences
	customize_preference_menu = "scheduler-customize-preference-menu",
	scheduler_customize_preference_view = "scheduler-customize-preference-view",
	customize_preference_edit = "scheduler-customize-preference-edit",
	// Assignment
	assignment_menu = "scheduler-assignment-menu",
	scheduler_assignment_view = 'scheduler-assignment-view',
	scheduler_assignment_add_new = 'scheduler-assignment-add-new',
	scheduler_assignment_edit = 'scheduler-assignment-edit',
	scheduler_assignment_delete = 'scheduler-assignment-delete',
	notification_menu = "scheduler-assignment-notification",
	// Waiting List Provider
	waiting_list_doctor_menu = "scheduler-waiting-list-doctor-menu",
	scheduler_waiting_list_doctor_view = "scheduler-waiting-list-doctor-view",
	waiting_list_appointment_add = "scheduler-waiting-list-doctor-appointemnt-add",
}
