let data = {
    "message": "success",
    "status": 200,
    "data": {
        "id": 10,
        "key": null,
        "patient_id": 10,
        "case_type_id": 4,
        "category_id": 1,
        "purpose_of_visit_id": 3,
        "practice_id": 1,
        "created_by": null,
        "updated_by": null,
        "created_at": "2020-02-03T06:31:51.000Z",
        "updated_at": "2020-02-03T06:31:51.000Z",
        "deleted_at": null,
        "patient": {
            "id": 10,
            "key": null,
            "first_name": "patients_first",
            "middle_name": "patients_middle",
            "last_name": "patients_last",
            "dob": "2019-09-27T20:00:00.000Z",
            "gender": "male",
            "age": 12,
            "ssn": "123123",
            "height_ft": 12,
            "height_in": 14,
            "weight_lbs": 12.4,
            "weight_kg": null,
            "meritial_status": "single",
            "profile_avatar": null,
            "need_translator": 0,
            "language": "english",
            "is_pregnant": "yes",
            "created_by": null,
            "updated_by": null,
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        "basic_information": {
            "id": 68,
            "key": null,
            "case_id": 10,
            "contact_person_type_id": 1,
            "contact_person_relation_id": null,
            "other_relation_description": null,
            "first_name": "self",
            "middle_name": "self",
            "last_name": "self",
            "ssn": null,
            "dob": "2019-09-28",
            "age": null,
            "gender": null,
            "email": "abcd@gmail.com",
            "fax": "09909",
            "cell_phone": "2323232",
            "home_phone": "",
            "work_phone": "",
            "ext": null,
            "height_in": null,
            "height_ft": null,
            "weight_lbs": null,
            "weight_kg": null,
            "marital_status": null,
            "is_resedential_same": 0,
            "is_emergency": 0,
            "is_guarantor": 0,
            "workplace_name": null,
            "Object_id": 10,
            "created_by": null,
            "updated_by": null,
            "created_at": "2020-02-03T06:31:52.000Z",
            "updated_at": "2020-02-03T06:31:52.000Z",
            "deleted_at": null,
            "contactPersonType": {
                "id": 1,
                "key": null,
                "name": "Self",
                "slug": "self",
                "created_by": null,
                "updated_by": null,
                "created_at": "2019-10-16T12:58:23.000Z",
                "updated_at": "2019-10-16T12:58:23.000Z",
                "deleted_at": null
            },
            "contactPersonRelation": null,
            "mail_address": {
                "id": 66,
                "key": null,
                "contact_person_id": 68,
                "type": "mailing",
                "street": "assis123",
                "apartment": "assis",
                "latitude": null,
                "longitude": null,
                "city": "",
                "state": "",
                "zip": "54000",
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:31:53.000Z",
                "updated_at": "2020-02-03T06:31:53.000Z",
                "deleted_at": null
            },
            "residential_address": {
                "id": 67,
                "key": null,
                "contact_person_id": 68,
                "type": "residential",
                "street": "assis",
                "apartment": "assis",
                "latitude": null,
                "longitude": null,
                "city": "",
                "state": "",
                "zip": "54000",
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:31:53.000Z",
                "updated_at": "2020-02-03T06:31:53.000Z",
                "deleted_at": null
            }
        },
        "form_filler_information": {
            "id": 69,
            "key": null,
            "case_id": 10,
            "contact_person_type_id": 2,
            "contact_person_relation_id": null,
            "other_relation_description": "description",
            "first_name": "form_filler",
            "middle_name": "form_filler",
            "last_name": "form_filler",
            "ssn": null,
            "dob": "2019-09-28",
            "age": null,
            "gender": null,
            "email": "abcd@gmail.com",
            "fax": "09909",
            "cell_phone": "2323232",
            "home_phone": null,
            "work_phone": null,
            "ext": null,
            "height_in": null,
            "height_ft": null,
            "weight_lbs": null,
            "weight_kg": null,
            "marital_status": null,
            "is_resedential_same": null,
            "is_emergency": 0,
            "is_guarantor": 0,
            "workplace_name": null,
            "Object_id": 10,
            "created_by": null,
            "updated_by": null,
            "created_at": "2020-02-03T06:31:54.000Z",
            "updated_at": "2020-02-03T06:31:54.000Z",
            "deleted_at": null,
            "contactPersonType": {
                "id": 2,
                "key": null,
                "name": "Form Filler",
                "slug": "form_filler",
                "created_by": null,
                "updated_by": null,
                "created_at": "2019-10-16T12:58:23.000Z",
                "updated_at": "2019-10-16T12:58:23.000Z",
                "deleted_at": null
            },
            "contactPersonRelation": null,
            "mail_address": {
                "id": 68,
                "key": null,
                "contact_person_id": 69,
                "type": "mailing",
                "street": "formfiller street",
                "apartment": "formfiller apartment",
                "latitude": null,
                "longitude": null,
                "city": "formfiller city",
                "state": "formfiller state",
                "zip": "54000",
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:31:54.000Z",
                "updated_at": "2020-02-03T06:31:54.000Z",
                "deleted_at": null
            },
            "residential_address": null
        },
        "emergency_information": {
            "id": 70,
            "key": null,
            "case_id": 10,
            "contact_person_type_id": 3,
            "contact_person_relation_id": 1,
            "other_relation_description": null,
            "first_name": "emergency",
            "middle_name": "aasd",
            "last_name": "asd",
            "ssn": null,
            "dob": "2019-09-28",
            "age": null,
            "gender": null,
            "email": "1213@gmail.com",
            "fax": "56566",
            "cell_phone": "897979",
            "home_phone": "90777623",
            "work_phone": null,
            "ext": null,
            "height_in": null,
            "height_ft": null,
            "weight_lbs": null,
            "weight_kg": null,
            "marital_status": null,
            "is_resedential_same": 1,
            "is_emergency": 0,
            "is_guarantor": 0,
            "workplace_name": null,
            "Object_id": 10,
            "created_by": null,
            "updated_by": null,
            "created_at": "2020-02-03T06:31:55.000Z",
            "updated_at": "2020-02-03T06:31:55.000Z",
            "deleted_at": null,
            "contactPersonType": {
                "id": 3,
                "key": null,
                "name": "Emergency",
                "slug": "emergency",
                "created_by": null,
                "updated_by": null,
                "created_at": "2019-10-16T12:58:23.000Z",
                "updated_at": "2019-10-16T12:58:23.000Z",
                "deleted_at": null
            },
            "contactPersonRelation": {
                "id": 1,
                "key": null,
                "name": "Father",
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-01-29T08:52:17.000Z",
                "updated_at": "2020-01-29T08:52:17.000Z",
                "deleted_at": null
            },
            "mail_address": {
                "id": 69,
                "key": null,
                "contact_person_id": 70,
                "type": "mailing",
                "street": "emergency street",
                "apartment": "emergency apartment",
                "latitude": null,
                "longitude": null,
                "city": "emergency city",
                "state": "emergency state",
                "zip": "54000",
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:31:55.000Z",
                "updated_at": "2020-02-03T06:31:55.000Z",
                "deleted_at": null
            },
            "residential_address": null
        },
        "guarantor_information": {
            "id": 71,
            "key": null,
            "case_id": 10,
            "contact_person_type_id": 4,
            "contact_person_relation_id": 2,
            "other_relation_description": null,
            "first_name": "guarantor_contact_information",
            "middle_name": "aasd",
            "last_name": "asd",
            "ssn": "998",
            "dob": "2019-09-28",
            "age": null,
            "gender": "male",
            "email": "gmd@sdfs.com",
            "fax": "232",
            "cell_phone": "232ef",
            "home_phone": "2334923",
            "work_phone": null,
            "ext": null,
            "height_in": null,
            "height_ft": null,
            "weight_lbs": null,
            "weight_kg": null,
            "marital_status": null,
            "is_resedential_same": null,
            "is_emergency": 0,
            "is_guarantor": 0,
            "workplace_name": null,
            "Object_id": 10,
            "created_by": null,
            "updated_by": null,
            "created_at": "2020-02-03T06:31:57.000Z",
            "updated_at": "2020-02-03T06:31:57.000Z",
            "deleted_at": null,
            "contactPersonType": {
                "id": 4,
                "key": null,
                "name": "Guarantor",
                "slug": "guarantor",
                "created_by": null,
                "updated_by": null,
                "created_at": "2019-10-21T11:34:27.000Z",
                "updated_at": "2019-10-21T11:34:27.000Z",
                "deleted_at": null
            },
            "contactPersonRelation": {
                "id": 2,
                "key": null,
                "name": "Mother",
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-01-29T08:52:17.000Z",
                "updated_at": "2020-01-29T08:52:17.000Z",
                "deleted_at": null
            },
            "mail_address": {
                "id": 70,
                "key": null,
                "contact_person_id": 71,
                "type": "mailing",
                "street": "guarantor street",
                "apartment": "guarantor apartment",
                "latitude": null,
                "longitude": null,
                "city": "guarantor city",
                "state": "guarantor state",
                "zip": "54000",
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:31:57.000Z",
                "updated_at": "2020-02-03T06:31:57.000Z",
                "deleted_at": null
            },
            "residential_address": null
        },
        "insurance": {
            "primary_insurance": {
                "id": 24,
                "first_name": "primary_firstname",
                "middle_name": "primary_middle_name",
                "last_name": "primary_last_name",
                "claim_no": "12313",
                "policy_no": "21313",
                "wcb_no": "123213",
                "member_id": null,
                "group_no": null,
                "insurance_company": {
                    "id": 217,
                    "name": "asdasddsd",
                    "insurance_code": null,
                    "location_id": 326,
                    "street_address": "",
                    "apartment_suite": "",
                    "city": "",
                    "state": "",
                    "zip": "54000",
                    "phone_no": null,
                    "cell_no": null,
                    "ext": null,
                    "fax": null
                },
                "adjustor": {
                    "id": 1794,
                    "adjustor_id": 35,
                    "first_name": null,
                    "middle_name": null,
                    "last_name": null,
                    "phone_no": null,
                    "ext": null,
                    "fax": null,
                    "email": "dummy",
                    "cell_no": null
                }
            },
            "secondary_insurance": {
                "id": 25,
                "first_name": "secondary_first_name",
                "middle_name": "secondary_middle_name",
                "last_name": "secondary_last_name",
                "claim_no": "",
                "policy_no": "",
                "wcb_no": "",
                "member_id": null,
                "group_no": null,
                "insurance_company": {
                    "id": 218,
                    "name": "",
                    "insurance_code": null,
                    "location_id": 327,
                    "street_address": "",
                    "apartment_suite": "",
                    "city": "",
                    "state": "",
                    "zip": "54000",
                    "phone_no": null,
                    "cell_no": null,
                    "ext": null,
                    "fax": null
                },
                "adjustor": {
                    "id": 1808,
                    "adjustor_id": 56,
                    "first_name": "secondary_first_name_adjustor",
                    "middle_name": "secondary_middle_name_adjustor",
                    "last_name": "secondary_last_name_adjustor",
                    "phone_no": "",
                    "ext": "",
                    "fax": "",
                    "email": "",
                    "cell_no": ""
                }
            },
            "tertiary_insurance": {
                "id": 26,
                "first_name": "yearly_first_name",
                "middle_name": "yearly_middle_name",
                "last_name": "yearly_last_name",
                "claim_no": "",
                "policy_no": "",
                "wcb_no": "",
                "member_id": null,
                "group_no": null,
                "insurance_company": {
                    "id": 219,
                    "name": "",
                    "insurance_code": null,
                    "location_id": 328,
                    "street_address": "",
                    "apartment_suite": "",
                    "city": "",
                    "state": "",
                    "zip": "54000",
                    "phone_no": null,
                    "cell_no": null,
                    "ext": null,
                    "fax": null
                },
                "adjustor": {
                    "id": 1809,
                    "adjustor_id": 57,
                    "first_name": "yearly_first_name_adjustor",
                    "middle_name": "yearly_middle_name_adjustor",
                    "last_name": "yearly_last_name_adjustor",
                    "phone_no": "",
                    "ext": "",
                    "fax": "",
                    "email": "",
                    "cell_no": ""
                }
            },
            "private_health_insurance": {
                "id": 23,
                "first_name": "private_health",
                "middle_name": "private_health",
                "last_name": "private_health",
                "claim_no": null,
                "policy_no": null,
                "wcb_no": null,
                "member_id": "123123",
                "group_no": "123123",
                "insurance_company": {
                    "id": 193,
                    "name": "hello",
                    "insurance_code": "123",
                    "location_id": 286,
                    "street_address": "dummy",
                    "apartment_suite": "dummy",
                    "city": "dummy",
                    "state": "dummy",
                    "zip": "123",
                    "phone_no": "123123",
                    "cell_no": "123123",
                    "ext": "123123",
                    "fax": "123123"
                }
            }
        },
        "attorney": {
            "id": 9,
            "key": null,
            "case_id": 10,
            "attorney_id": 1,
            "firm_id": 1,
            "firm_location_id": 89,
            "created_by": null,
            "updated_by": null,
            "created_at": "2020-02-03T06:32:00.000Z",
            "updated_at": "2020-02-03T06:32:00.000Z",
            "deleted_at": null,
            "attorney": {
                "id": 1,
                "first_name": "sd",
                "middle_name": null,
                "last_name": "sds",
                "street_address": "77 Warren Street",
                "suit_floor": "rrui",
                "city": "Boston",
                "state": "Massachusetts",
                "zip": "2135",
                "phone_no": null,
                "ext": null,
                "cell_no": "1212344454",
                "fax": null,
                "email": null,
                "comments": null,
                "created_at": "2019-10-22T05:47:47.000Z",
                "updated_at": "2019-10-22T12:12:37.000Z",
                "deleted_at": null,
                "created_by": null,
                "updated_by": null
            },
            "firm": {
                "id": 1,
                "name": "Test",
                "created_at": "2019-10-22T12:56:57.000Z",
                "updated_at": "2019-10-22T12:56:57.000Z",
                "deleted_at": null,
                "created_by": null,
                "updated_by": null
            },
            "firmLocation": {
                "id": 89,
                "firm_id": 1,
                "location_name": "new location",
                "street_address": null,
                "apartment_suite": null,
                "city": null,
                "state": null,
                "zip": null,
                "created_at": null,
                "updated_at": null,
                "deleted_at": null,
                "phone": null,
                "cell": null,
                "ext": null,
                "fax": null,
                "email": null,
                "contact_person_first_name": null,
                "contact_person_middle_name": null,
                "contact_person_last_name": null,
                "contact_person_phone": null,
                "contact_person_cell": null,
                "contact_person_ext": null,
                "contact_person_fax": null,
                "contact_person_email": null,
                "comments": null,
                "is_main": 0,
                "place_of_service_id": null
            },
            "contact_person": {
                "id": 72,
                "key": null,
                "case_id": 10,
                "contact_person_type_id": 5,
                "contact_person_relation_id": null,
                "other_relation_description": null,
                "first_name": "name",
                "middle_name": "name",
                "last_name": "name",
                "ssn": null,
                "dob": null,
                "age": null,
                "gender": null,
                "email": null,
                "fax": null,
                "cell_phone": null,
                "home_phone": null,
                "work_phone": null,
                "ext": null,
                "height_in": null,
                "height_ft": null,
                "weight_lbs": null,
                "weight_kg": null,
                "marital_status": null,
                "is_resedential_same": null,
                "is_emergency": 0,
                "is_guarantor": 0,
                "workplace_name": null,
                "Object_id": 1,
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:31:59.000Z",
                "updated_at": "2020-02-03T06:31:59.000Z",
                "deleted_at": null,
                "contactPersonAddresses": [],
                "contactPersonType": {
                    "id": 5,
                    "key": null,
                    "name": "Attorney",
                    "slug": "attorney",
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2019-10-22T06:21:20.000Z",
                    "updated_at": "2019-10-22T06:21:20.000Z",
                    "deleted_at": null
                },
                "contactPersonRelation": null
            }
        },
        "employer": {
            "case_employers": [
                {
                    "id": 14,
                    "key": null,
                    "case_id": 10,
                    "employer_id": 15,
                    "employer_type_id": 1,
                    "occupation": "occupation",
                    "date_hired": "2019-09-28",
                    "end_Date": null,
                    "is_time_looses": 1,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2020-02-03T06:32:10.000Z",
                    "updated_at": "2020-02-03T06:32:10.000Z",
                    "deleted_at": null,
                    "caseEmployerType": {
                        "id": 1,
                        "key": null,
                        "name": "primary",
                        "created_by": null,
                        "updated_by": null,
                        "created_at": null,
                        "updated_at": null,
                        "deleted_at": null
                    },
                    "employer": {
                        "id": 15,
                        "employer_name": "emp_name",
                        "street_address": "street_address11",
                        "apartment_suite": "apartment_suite2",
                        "city": "city3",
                        "state": "state4",
                        "zip": "540005",
                        "contactPersonFirstName": null,
                        "contactPersonMiddleName": null,
                        "contactPersonLastName": null,
                        "contactPersonPhoneNo": null,
                        "contactPersonExt": null,
                        "contactPersonFax": null,
                        "contactPersonEmail": null,
                        "comments": null,
                        "created_at": "2020-02-03T06:32:09.000Z",
                        "updated_at": "2020-02-03T06:32:09.000Z",
                        "deletedAt": null,
                        "isDeleted": null,
                        "created_by": null,
                        "updated_by": null
                    }
                },
                {
                    "id": 15,
                    "key": null,
                    "case_id": 10,
                    "employer_id": 6,
                    "employer_type_id": 2,
                    "occupation": "occupation",
                    "date_hired": "2019-09-28",
                    "end_Date": "2019-09-28",
                    "is_time_looses": 0,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2020-02-03T06:32:11.000Z",
                    "updated_at": "2020-02-03T06:32:11.000Z",
                    "deleted_at": null,
                    "caseEmployerType": {
                        "id": 2,
                        "key": null,
                        "name": "secondary",
                        "created_by": null,
                        "updated_by": null,
                        "created_at": null,
                        "updated_at": null,
                        "deleted_at": null
                    },
                    "employer": {
                        "id": 6,
                        "employer_name": "shansa",
                        "street_address": "1135 East State Road 434",
                        "apartment_suite": "erer",
                        "city": "Winter Springs",
                        "state": "Florida",
                        "zip": "32708",
                        "contactPersonFirstName": "22",
                        "contactPersonMiddleName": "222",
                        "contactPersonLastName": "222",
                        "contactPersonPhoneNo": "2222222222",
                        "contactPersonExt": "2222222222",
                        "contactPersonFax": "2222222222",
                        "contactPersonEmail": "22@ed",
                        "comments": "warfwa",
                        "created_at": "2020-01-31T11:56:51.000Z",
                        "updated_at": "2020-01-31T11:56:51.000Z",
                        "deletedAt": null,
                        "isDeleted": null,
                        "created_by": 2,
                        "updated_by": null
                    }
                },
                {
                    "id": 16,
                    "key": null,
                    "case_id": 10,
                    "employer_id": 16,
                    "employer_type_id": 2,
                    "occupation": "occupation",
                    "date_hired": "2019-09-28",
                    "end_Date": "2019-09-28",
                    "is_time_looses": 0,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2020-02-03T06:32:11.000Z",
                    "updated_at": "2020-02-03T06:32:11.000Z",
                    "deleted_at": null,
                    "caseEmployerType": {
                        "id": 2,
                        "key": null,
                        "name": "secondary",
                        "created_by": null,
                        "updated_by": null,
                        "created_at": null,
                        "updated_at": null,
                        "deleted_at": null
                    },
                    "employer": {
                        "id": 16,
                        "employer_name": "secondary_employer2",
                        "street_address": "street_address",
                        "apartment_suite": "apartment_suite",
                        "city": "city",
                        "state": "state",
                        "zip": "54000",
                        "contactPersonFirstName": null,
                        "contactPersonMiddleName": null,
                        "contactPersonLastName": null,
                        "contactPersonPhoneNo": null,
                        "contactPersonExt": null,
                        "contactPersonFax": null,
                        "contactPersonEmail": null,
                        "comments": null,
                        "created_at": "2020-02-03T06:32:11.000Z",
                        "updated_at": "2020-02-03T06:32:11.000Z",
                        "deletedAt": null,
                        "isDeleted": null,
                        "created_by": null,
                        "updated_by": null
                    }
                },
                {
                    "id": 17,
                    "key": null,
                    "case_id": 10,
                    "employer_id": 5,
                    "employer_type_id": 3,
                    "occupation": "occupation",
                    "date_hired": "2019-09-28",
                    "end_Date": "2019-09-28",
                    "is_time_looses": 0,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2020-02-03T06:32:12.000Z",
                    "updated_at": "2020-02-03T06:32:12.000Z",
                    "deleted_at": null,
                    "caseEmployerType": {
                        "id": 3,
                        "key": null,
                        "name": "yearly",
                        "created_by": null,
                        "updated_by": null,
                        "created_at": null,
                        "updated_at": null,
                        "deleted_at": null
                    },
                    "employer": {
                        "id": 5,
                        "employer_name": "New Employee",
                        "street_address": "12888 Highway 6",
                        "apartment_suite": "2nddd",
                        "city": "Sugar Land",
                        "state": "Texas",
                        "zip": "77498",
                        "contactPersonFirstName": "shansa",
                        "contactPersonMiddleName": "mid",
                        "contactPersonLastName": "last",
                        "contactPersonPhoneNo": "2132312312",
                        "contactPersonExt": "213213",
                        "contactPersonFax": "3123213213",
                        "contactPersonEmail": "123@34",
                        "comments": "comment",
                        "created_at": "2020-01-30T13:20:13.000Z",
                        "updated_at": "2020-01-30T13:20:39.000Z",
                        "deletedAt": null,
                        "isDeleted": null,
                        "created_by": 2,
                        "updated_by": 2
                    }
                },
                {
                    "id": 18,
                    "key": null,
                    "case_id": 10,
                    "employer_id": 17,
                    "employer_type_id": 3,
                    "occupation": "occupation",
                    "date_hired": "2019-09-28",
                    "end_Date": "2019-09-28",
                    "is_time_looses": 0,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2020-02-03T06:32:12.000Z",
                    "updated_at": "2020-02-03T06:32:12.000Z",
                    "deleted_at": null,
                    "caseEmployerType": {
                        "id": 3,
                        "key": null,
                        "name": "yearly",
                        "created_by": null,
                        "updated_by": null,
                        "created_at": null,
                        "updated_at": null,
                        "deleted_at": null
                    },
                    "employer": {
                        "id": 17,
                        "employer_name": "yearly_employer2",
                        "street_address": "street_address",
                        "apartment_suite": "apartment_suite",
                        "city": "city",
                        "state": "state",
                        "zip": "54000",
                        "contactPersonFirstName": null,
                        "contactPersonMiddleName": null,
                        "contactPersonLastName": null,
                        "contactPersonPhoneNo": null,
                        "contactPersonExt": null,
                        "contactPersonFax": null,
                        "contactPersonEmail": null,
                        "comments": null,
                        "created_at": "2020-02-03T06:32:12.000Z",
                        "updated_at": "2020-02-03T06:32:12.000Z",
                        "deletedAt": null,
                        "isDeleted": null,
                        "created_by": null,
                        "updated_by": null
                    }
                }
            ],
            "employment_information": {
                "id": 3,
                "key": null,
                "case_id": 10,
                "title": "title",
                "activities": "activities",
                "type": "full_time",
                "type_description": "type_description",
                "receive_lodging": 1,
                "lodging_description": "lodging_description",
                "gross_salary": 123,
                "often_paid": "Weekly",
                "course_of_employment": 1,
                "unemployment_benefits": 1,
                "weekly_earning": 1334,
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:32:12.000Z",
                "updated_at": "2020-02-03T06:32:12.000Z",
                "deleted_at": null,
                "no_of_hours_per_day": 12,
                "no_of_days_per_week": 1
            },
            "return_to_work": {
                "id": 1,
                "key": null,
                "case_id": 10,
                "work_stop": 0,
                "work_stop_date": "2019-09-27T20:00:00.000Z",
                "return_to_work": 1,
                "return_to_work_date": "2019-09-27T20:00:00.000Z",
                "current_employment_status": "new_employer",
                "type_of_assignment": "limited_duty",
                "illness_notice": 1,
                "illness_notice_date": "2019-09-27T20:00:00.000Z",
                "given_notice_type": "in_writing",
                "contact_person_id": 78,
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:32:18.000Z",
                "updated_at": "2020-02-03T06:32:18.000Z",
                "deleted_at": null
            }
        },
        "accident_information": {
            "id": 3,
            "key": null,
            "case_id": 10,
            "accident_date": "2019-09-27T20:00:00.000Z",
            "accident_time": "",
            "patient_at_time_of_accident": "taxi_driver",
            "at_time_of_accident_other_description": "",
            "usual_work_location": 1,
            "location_reason": "",
            "accident_location": "",
            "accident_happend": "",
            "street_no": "",
            "city": "",
            "state": "",
            "zip": "54000",
            "nature_of_accident": "",
            "activity_at_injury": "",
            "injury_description": "",
            "injured_at_work_location": 1,
            "case_established": "",
            "had_ime": null,
            "created_by": null,
            "updated_by": null,
            "created_at": "2020-02-03T06:32:13.000Z",
            "updated_at": "2020-02-03T06:32:13.000Z",
            "deleted_at": null,
            "object_involved": {
                "id": 3,
                "key": null,
                "case_id": 10,
                "object_involved": 0,
                "object_involved_description": "",
                "vehicle_involved": 1,
                "vehicle_belongs_to": "patient",
                "driver_was": "taxi",
                "accident_reported": 1,
                "reporting_date": "2019-09-27T20:00:00.000Z",
                "precinct": "",
                "state": "",
                "city": "",
                "country": null,
                "was_this": "employer",
                "was_this_description": "",
                "vehicle_was": "motor_cycle",
                "no_of_vehicle_involved": 4,
                "vehicle_patient_were_in": 2,
                "was_this_car": "none",
                "also_owner_of_vehicle": 0,
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:32:14.000Z",
                "updated_at": "2020-02-03T06:32:14.000Z",
                "deleted_at": null
            },
            "witnesses": [
                {
                    "id": 79,
                    "key": null,
                    "case_id": 10,
                    "contact_person_type_id": 12,
                    "contact_person_relation_id": null,
                    "other_relation_description": null,
                    "first_name": "Abubakar",
                    "middle_name": "Adam",
                    "last_name": "Saddique",
                    "ssn": null,
                    "dob": null,
                    "age": null,
                    "gender": null,
                    "email": null,
                    "fax": null,
                    "cell_phone": null,
                    "home_phone": null,
                    "work_phone": null,
                    "ext": null,
                    "height_in": null,
                    "height_ft": null,
                    "weight_lbs": null,
                    "weight_kg": null,
                    "marital_status": null,
                    "is_resedential_same": null,
                    "is_emergency": 0,
                    "is_guarantor": 0,
                    "workplace_name": null,
                    "Object_id": 10,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2020-02-03T06:32:19.000Z",
                    "updated_at": "2020-02-03T06:32:19.000Z",
                    "deleted_at": null,
                    "contactPersonAddresses": [
                        {
                            "id": 75,
                            "key": null,
                            "contact_person_id": 79,
                            "type": "mailing",
                            "street": "42 street, QuickBills MD",
                            "apartment": null,
                            "latitude": null,
                            "longitude": null,
                            "city": "Lahore",
                            "state": "Punjab",
                            "zip": "45000",
                            "created_by": null,
                            "updated_by": null,
                            "created_at": "2020-02-03T06:32:19.000Z",
                            "updated_at": "2020-02-03T06:32:19.000Z",
                            "deleted_at": null
                        }
                    ],
                    "contactPersonType": {
                        "id": 12,
                        "key": null,
                        "name": "Witness to accident",
                        "slug": "witness_to_accident",
                        "created_by": null,
                        "updated_by": null,
                        "created_at": "2019-11-13T09:23:58.000Z",
                        "updated_at": "2019-11-13T09:23:58.000Z",
                        "deleted_at": null
                    },
                    "contactPersonRelation": null
                },
                {
                    "id": 80,
                    "key": null,
                    "case_id": 10,
                    "contact_person_type_id": 12,
                    "contact_person_relation_id": null,
                    "other_relation_description": null,
                    "first_name": "Muhammad",
                    "middle_name": "Zack",
                    "last_name": "Muaz",
                    "ssn": null,
                    "dob": null,
                    "age": null,
                    "gender": null,
                    "email": null,
                    "fax": null,
                    "cell_phone": null,
                    "home_phone": null,
                    "work_phone": null,
                    "ext": null,
                    "height_in": null,
                    "height_ft": null,
                    "weight_lbs": null,
                    "weight_kg": null,
                    "marital_status": null,
                    "is_resedential_same": null,
                    "is_emergency": 0,
                    "is_guarantor": 0,
                    "workplace_name": null,
                    "Object_id": 10,
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2020-02-03T06:32:20.000Z",
                    "updated_at": "2020-02-03T06:32:20.000Z",
                    "deleted_at": null,
                    "contactPersonAddresses": [
                        {
                            "id": 76,
                            "key": null,
                            "contact_person_id": 80,
                            "type": "mailing",
                            "street": "142 street, QuickBills MD",
                            "apartment": null,
                            "latitude": null,
                            "longitude": null,
                            "city": "Lahore",
                            "state": "Punjab",
                            "zip": "45000",
                            "created_by": null,
                            "updated_by": null,
                            "created_at": "2020-02-03T06:32:20.000Z",
                            "updated_at": "2020-02-03T06:32:20.000Z",
                            "deleted_at": null
                        }
                    ],
                    "contactPersonType": {
                        "id": 12,
                        "key": null,
                        "name": "Witness to accident",
                        "slug": "witness_to_accident",
                        "created_by": null,
                        "updated_by": null,
                        "created_at": "2019-11-13T09:23:58.000Z",
                        "updated_at": "2019-11-13T09:23:58.000Z",
                        "deleted_at": null
                    },
                    "contactPersonRelation": null
                }
            ]
        },
        "physician": {
            "reffering_physician": {
                "id": 73,
                "key": null,
                "case_id": 10,
                "contact_person_type_id": 6,
                "contact_person_relation_id": null,
                "other_relation_description": null,
                "first_name": "name",
                "middle_name": "name",
                "last_name": "name",
                "ssn": null,
                "dob": null,
                "age": null,
                "gender": null,
                "email": "",
                "fax": "",
                "cell_phone": "",
                "home_phone": null,
                "work_phone": null,
                "ext": "",
                "height_in": null,
                "height_ft": null,
                "weight_lbs": null,
                "weight_kg": null,
                "marital_status": null,
                "is_resedential_same": null,
                "is_emergency": 0,
                "is_guarantor": 0,
                "workplace_name": "",
                "Object_id": 10,
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:32:01.000Z",
                "updated_at": "2020-02-03T06:32:01.000Z",
                "deleted_at": null,
                "contactPersonType": {
                    "id": 6,
                    "key": null,
                    "name": "Reffering physician",
                    "slug": "reffering_physician",
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2019-10-22T09:15:09.000Z",
                    "updated_at": "2019-10-22T09:15:09.000Z",
                    "deleted_at": null
                },
                "contactPersonRelation": null,
                "mail_address": {
                    "id": 71,
                    "key": null,
                    "contact_person_id": 73,
                    "type": "mailing",
                    "street": "reffering physician street",
                    "apartment": "reffering physician apartment",
                    "latitude": null,
                    "longitude": null,
                    "city": "reffering physician city",
                    "state": "reffering state",
                    "zip": "54000",
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2020-02-03T06:32:01.000Z",
                    "updated_at": "2020-02-03T06:32:01.000Z",
                    "deleted_at": null
                },
                "residential_address": null
            },
            "primary_physician": {
                "id": 74,
                "key": null,
                "case_id": 10,
                "contact_person_type_id": 7,
                "contact_person_relation_id": null,
                "other_relation_description": null,
                "first_name": "name",
                "middle_name": "name",
                "last_name": "name",
                "ssn": null,
                "dob": null,
                "age": null,
                "gender": null,
                "email": "",
                "fax": "",
                "cell_phone": "",
                "home_phone": null,
                "work_phone": null,
                "ext": "",
                "height_in": null,
                "height_ft": null,
                "weight_lbs": null,
                "weight_kg": null,
                "marital_status": null,
                "is_resedential_same": null,
                "is_emergency": 0,
                "is_guarantor": 0,
                "workplace_name": "",
                "Object_id": 10,
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:32:02.000Z",
                "updated_at": "2020-02-03T06:32:02.000Z",
                "deleted_at": null,
                "contactPersonType": {
                    "id": 7,
                    "key": null,
                    "name": "Primary Physician",
                    "slug": "primary_physician",
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2019-10-22T09:19:13.000Z",
                    "updated_at": "2019-10-22T09:19:13.000Z",
                    "deleted_at": null
                },
                "contactPersonRelation": null,
                "mail_address": {
                    "id": 72,
                    "key": null,
                    "contact_person_id": 74,
                    "type": "mailing",
                    "street": "reffering primary street",
                    "apartment": "reffering primary apartment",
                    "latitude": null,
                    "longitude": null,
                    "city": "reffering primary city",
                    "state": "reffering primary state",
                    "zip": "54000",
                    "created_by": null,
                    "updated_by": null,
                    "created_at": "2020-02-03T06:32:03.000Z",
                    "updated_at": "2020-02-03T06:32:03.000Z",
                    "deleted_at": null
                },
                "residential_address": null
            }
        },
        "medical_treatment": {
            "id": 1,
            "key": null,
            "date_of_first_treatment": "2019-09-27T20:00:00.000Z",
            "treated_on_site": 1,
            "treated_on_site_date": "2019-09-27T20:00:00.000Z",
            "treated_off_site": 1,
            "first_off_site_treatment_location": "doctor_office",
            "date_of_admission": "2019-09-27T20:00:00.000Z",
            "same_injury_body_part": 1,
            "is_prev_injury_work_related": 1,
            "same_employer": 1,
            "had_ime": 1,
            "have_any_first_treatment": 1,
            "case_id": 10,
            "hospital_id": 1,
            "created_by": null,
            "updated_by": null,
            "created_at": "2020-02-03T06:32:27.000Z",
            "updated_at": "2020-02-03T06:32:27.000Z",
            "deleted_at": null,
            "general_details": {
                "id": 3,
                "injury_covered": 1,
                "injury_covered_insurance_id": 5,
                "eligible_for_payments": "worker_compensation",
                "worker_compensation_insurance_id": 4,
                "amount_of_bills": 1313,
                "same_injury": 1,
                "more_health_treatment": 1,
                "other_expenses": 1,
                "expense_description": "",
                "case_id": 10,
                "created_by": null,
                "updated_by": null,
                "created_at": "2020-02-03T06:32:13.000Z",
                "updated_at": "2020-02-03T06:32:13.000Z",
                "deleted_at": null
            },
            "doctor_details_for_current_injury": [
                {
                    "id": 1,
                    "medical_treatment_id": 1,
                    "contact_person_id": 83,
                    "contactPersons": {
                        "id": 83,
                        "key": null,
                        "case_id": 10,
                        "contact_person_type_id": 14,
                        "contact_person_relation_id": null,
                        "other_relation_description": null,
                        "first_name": "Ahmad",
                        "middle_name": "ad",
                        "last_name": "Butt",
                        "ssn": null,
                        "dob": null,
                        "age": null,
                        "gender": null,
                        "email": null,
                        "fax": null,
                        "cell_phone": null,
                        "home_phone": null,
                        "work_phone": null,
                        "ext": null,
                        "height_in": null,
                        "height_ft": null,
                        "weight_lbs": null,
                        "weight_kg": null,
                        "marital_status": null,
                        "is_resedential_same": null,
                        "is_emergency": 0,
                        "is_guarantor": 0,
                        "workplace_name": null,
                        "Object_id": 10,
                        "created_by": null,
                        "updated_by": null,
                        "created_at": "2020-02-03T06:32:25.000Z",
                        "updated_at": "2020-02-03T06:32:25.000Z",
                        "deleted_at": null,
                        "contactPersonType": {
                            "id": 14,
                            "key": null,
                            "name": "Current treated by",
                            "slug": "current_treated_by",
                            "created_by": null,
                            "updated_by": null,
                            "created_at": "2019-11-14T15:26:43.000Z",
                            "updated_at": "2019-11-14T15:26:43.000Z",
                            "deleted_at": null
                        },
                        "contactPersonAddresses": [
                            {
                                "id": 77,
                                "key": null,
                                "contact_person_id": 83,
                                "type": "mailing",
                                "street": "142 street, st MD",
                                "apartment": "33-C IBSGX",
                                "latitude": null,
                                "longitude": null,
                                "city": "Lahore",
                                "state": "Punjab",
                                "zip": "45000",
                                "created_by": null,
                                "updated_by": null,
                                "created_at": "2020-02-03T06:32:25.000Z",
                                "updated_at": "2020-02-03T06:32:25.000Z",
                                "deleted_at": null
                            }
                        ]
                    }
                }
            ],
            "doctor_details_for_previous_injury": [
                {
                    "id": 2,
                    "medical_treatment_id": 1,
                    "contact_person_id": 84,
                    "contactPersons": {
                        "id": 84,
                        "key": null,
                        "case_id": 10,
                        "contact_person_type_id": 16,
                        "contact_person_relation_id": null,
                        "other_relation_description": null,
                        "first_name": "was",
                        "middle_name": "asd",
                        "last_name": "Qureshi",
                        "ssn": null,
                        "dob": null,
                        "age": null,
                        "gender": null,
                        "email": null,
                        "fax": null,
                        "cell_phone": null,
                        "home_phone": null,
                        "work_phone": null,
                        "ext": null,
                        "height_in": null,
                        "height_ft": null,
                        "weight_lbs": null,
                        "weight_kg": null,
                        "marital_status": null,
                        "is_resedential_same": null,
                        "is_emergency": 0,
                        "is_guarantor": 0,
                        "workplace_name": null,
                        "Object_id": 10,
                        "created_by": null,
                        "updated_by": null,
                        "created_at": "2020-02-03T06:32:27.000Z",
                        "updated_at": "2020-02-03T06:32:27.000Z",
                        "deleted_at": null,
                        "contactPersonType": {
                            "id": 16,
                            "key": null,
                            "name": "Previous treated by",
                            "slug": "previous_treated_by",
                            "created_by": null,
                            "updated_by": null,
                            "created_at": "2019-11-14T15:27:35.000Z",
                            "updated_at": "2019-11-14T15:27:35.000Z",
                            "deleted_at": null
                        },
                        "contactPersonAddresses": [
                            {
                                "id": 78,
                                "key": null,
                                "contact_person_id": 84,
                                "type": "mailing",
                                "street": "14 street, R town",
                                "apartment": "2-C RR Heights",
                                "latitude": null,
                                "longitude": null,
                                "city": "Lahore",
                                "state": "Punjab",
                                "zip": "45000",
                                "created_by": null,
                                "updated_by": null,
                                "created_at": "2020-02-03T06:32:27.000Z",
                                "updated_at": "2020-02-03T06:32:27.000Z",
                                "deleted_at": null
                            }
                        ]
                    }
                }
            ]
        }
    }
}

export default data;