export class CreateBillModalMockValues {
	getFormatedDocuments = {
		result: {
			data: [
				{
					id: 10,
					check: false,
				},
			],
			last_page: 2,
		},
	};
	mappingRespWithVisitLengthGreater1 = {
		appointment_id: 55,
		appointment_type: {},
		appointment_type_id: 90,
		bill_date: '2021-06-06',
		case_id: 21,
		cpt_codes: [{ id: 10 }],
		cpt_codes_comment: null,
		cpt_fee_schedules: [
			{
				code_id: 10,
				cpt_code: { id: 10 },
				fee_schedule_id: undefined,
				hasMultiplFee: true,
				id: undefined,
				modifiers: [],
				multiplefees: [
					{
						code_id: 10,
						cpt_code: { id: 10 },
						hasMultiplFee: true,
						modifiers: [],
						visit_id: 10,
					},
					{
						code_id: 10,
						cpt_code: { id: 10 },
						hasMultiplFee: true,
						modifiers: [],
						visit_id: 10,
					},
				],
				total_charges: NaN,
				visit_id: 10,
			},
		],
		doctor: {},
		doctor_id: 35,
		facility_location: {},
		facility_location_id: 89,
		icd_codes: [],
		icd_codes_comment: null,
		id: 10,
		kiosk_case: {
			accident_information: '',
			case_attorneys: [],
			case_categories: [],
			case_employers: {},
			case_insurances: {},
			case_type_id: 32,
			case_types: [],
			category_id: 89,
			id: 10,
			is_finalize: null,
			key: null,
			patient: [],
			patient_id: 77,
			practice_id: null,
			primary_insurance: [],
			purpose_of_visit: '',
			purpose_of_visit_id: 90,
			status: '',
		},
		no_of_days: 20,
		patient_id: 33,
		speciality: {},
		speciality_id: 55,
		visit_date: '2021-05-05',
		visit_date_format: '',
		visit_session_state: [],
		visit_session_state_id: 11,
		visit_type: null,
	};
	visitListMap: any = [{ id: 10 }];
	mappingFirstParam: any = [
		{
			id: 10,
			cpt_codes: [
				{
					id: 10,
					fee_schedules: [
						{ hasMultiplFee: false, code_id: 10 },
						{ hasMultiplFee: false, code_id: 10 },
					],
				},
			],
		},
	];
	mappingFirstParamIfFeeSchedulesLength1: any = [
		{
			id: 10,
			cpt_codes: [
				{
					id: 10,
					fee_schedules: [{ hasMultiplFee: false, code_id: 10 }],
				},
			],
		},
	];
	mappingSecondParam: any = [
		{
			id: 10,
			case_id: 21,
			patient_id: 33,
			doctor_id: 35,
			appointment_id: 55,
			speciality_id: 55,
			facility_location_id: 89,
			appointment_type_id: 90,
			visit_date: '2021-05-05',
			visit_session_state_id: 11,
			icd_codes_comment: null,
			cpt_codes_comment: null,
			visit_date_format: '',
			no_of_days: 20,
			kiosk_case: {
				id: 10,
				key: null,
				patient_id: 77,
				case_type_id: 32,
				category_id: 89,
				purpose_of_visit_id: 90,
				practice_id: null,
				is_finalize: null,
				status: '',
				case_types: [],
				patient: [],
				accident_information: '',
				case_categories: [],
				purpose_of_visit: '',
				case_attorneys: [],
				primary_insurance: [],
				case_insurances: {},
				case_employers: {},
			},
			visit_type: null,
			facility_location: {},
			speciality: {},
			appointment_type: {},
			visit_session_state: [],
			icd_codes: [],
			cpt_codes: [{ id: 10 }],
			bill_date: '2021-06-06',
			doctor: {},
			cpt_fee_schedules: [{ fee_schedule_id: false, cpt_code: { id: 10 } }],
		},
	];
	showModalParam = [
		{ name: 'mock_name1' },
		{ name: 'mock_name2' },
		{ name: 'mock_name3' },
		{ name: 'mock_name4' },
		{ name: 'mock_name5' },
		{ name: 'mock_name6' },
		{ name: 'mock_name7' },
	];
	calculateVisistLists = [
		{ visit_charges: 20, total_charges: 50, cpt_fee_schedules: [{ total_charges: 50 }] },
	];
	dropdownSettingResp = {
		singleSelection: false,
		idField: 'id',
		textField: 'name',
		selectAllText: 'Select All',
		unSelectAllText: 'UnSelect All',
		itemsShowLimit: 4,
		allowSearchFilter: false,
		enableCheckAll: true,
	};
	formatCheckData: any = {
		_results: [
			{
				checked: true,
			},
		],
	};
	formatCheckDataCheckedFalse: any = {
		_results: [
			{
				checked: true,
			},
		],
	};
	onFormatedCheckboxChangeVisist: any = [{ kiosk_case: { case_types: { slug: '1500' } } }];
	deletecptVisistList: any = [{ cpt_fee_schedules: [], isexpand: true }];
	confirmDeleteVisitListLengthGreater1: any = [
		{ visit_charges: 20, total_charges: 50, cpt_fee_schedules: [{ total_charges: 50 }] },
		{ visit_charges: 20, total_charges: 50, cpt_fee_schedules: [{ total_charges: 50 }] },
	];
	allSelectBillToRecpitient_1Resp = {
		bill_recipient_id: 10,
		bill_recipient_type_id: 1,
		document_type_ids: [21, 33],
	};
	allSelectBillToRecpitient_2Resp = {
		bill_recipient_id: 10,
		bill_recipient_type_id: 2,
		document_type_ids: [21, 33],
	};
	allSelectBillToRecpitient_3Resp = {
		bill_recipient_id: 10,
		bill_recipient_type_id: 3,
		document_type_ids: [21, 33],
	};
	allSelectBillToRecpitient_4Resp = {
		bill_recipient_id: 10,
		bill_recipient_type_id: 4,
		document_type_ids: [21, 33],
	};
	submitCreateBillFormParam = {
		bill_date: '2021-09-28',
		bill_recipients: [
			{
				created_by: null,
				description: 'patient',
				id: 1,
				name: 'Patient',
				slug: 'patient',
			},
			{
				created_by: null,
				description: 'Employer',
				id: 2,
				name: 'Employer',
				slug: 'employer',
			},
			{
				created_by: null,
				description: 'Insurance',
				id: 3,
				name: 'Insurance',
				slug: 'insurance',
			},
			{
				created_by: null,
				description: 'Lawyer',
				id: 4,
				name: 'Lawyer',
				slug: 'lawyer',
			},
		],
		case_id: 170,
		document_type_ids: [''],
		icd_code_ids: '',
		speciality_id: 2,
		visit_sessions: null,
	};
	submitCreateBillFormParamWithRecepientNull = {
		bill_date: '2021-09-28',
		bill_recipients: null,
		case_id: 170,
		document_type_ids: [''],
		icd_code_ids: '',
		speciality_id: 2,
		visit_sessions: null,
	};
	submitCreateBillFormParamWithBill_date_Null = {
		bill_date: null,
		bill_recipients: [
			{
				created_by: null,
				description: 'patient',
				id: 1,
				name: 'Patient',
				slug: 'patient',
			},
			{
				created_by: null,
				description: 'Employer',
				id: 2,
				name: 'Employer',
				slug: 'employer',
			},
			{
				created_by: null,
				description: 'Insurance',
				id: 3,
				name: 'Insurance',
				slug: 'insurance',
			},
			{
				created_by: null,
				description: 'Lawyer',
				id: 4,
				name: 'Lawyer',
				slug: 'lawyer',
			},
		],
		case_id: 170,
		document_type_ids: [''],
		icd_code_ids: '',
		speciality_id: 2,
		visit_sessions: null,
	};
	submitCreateBillFormVisitList: any = [
		{
			id: 116,
			case_id: 170,
			patient_id: 128,
			doctor_id: 38,
			appointment_id: 129,
			speciality_id: 2,
			facility_location_id: 14,
			appointment_type_id: 2,
			visit_date: '2020-06-26 12:40:00',
			visit_session_state_id: 3,
			icd_codes_comment: null,
			cpt_codes_comment: null,
			visit_charges: '344.50',
			doctor_signature_id: null,
			patient_signature_id: null,
			is_amended: 0,
			is_tm_updatable: 0,
			document_uploaded: 1,
			last_uploaded_document_date: '2021-04-08 09:02:57',
			visit_date_format: '2020-06-26',
			no_of_days: 462,
			billing_title: 'MD',
			pivot: {
				bill_id: 389,
				visit_session_id: 116,
			},
			cpt_fee_schedules: [
				{
					id: 321,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
			],
			appointment_type: {
				id: 2,
				name: 'FU',
				slug: 'follow_up',
				description: 'Test Comments124',
				created_by: null,
				updated_by: 1,
			},
			doctor: {
				id: 37,
				first_name: 'Mr',
				middle_name: 'Acu',
				last_name: 'Provider',
				user_id: 38,
			},
			facility_location: {
				id: 14,
				facility_id: 1,
				name: 'Test Location',
				city: 'Lahore',
				state: 'PW',
				zip: '54000',
				region_id: '1',
				address: '125 askari 9',
				phone: '1111111111',
				fax: '1111111111',
				email: 'test@mail.com',
				office_hours_start: null,
				office_hours_end: null,
				lat: 31.4681414,
				long: 74.4477643,
				day_list: '[0,1,2,3,4,5,6]',
				floor: '9/2A',
				place_of_service_id: 49,
				ext_no: null,
				cell_no: null,
				is_main: 0,
				same_as_provider: 0,
				created_by: 287,
				updated_by: 287,
				created_at: '2020-06-11 16:23:20',
				updated_at: '2021-08-26 08:15:21',
				deleted_at: null,
				facility_full_name: 'CitiMed - Test Location',
				facility: {
					id: 1,
					name: 'CitiMed',
					slug: 'citimed',
					created_by: 1,
					updated_by: 1,
				},
			},
			kiosk_case: {
				id: 170,
				key: null,
				patient_id: 128,
				case_type_id: 1,
				category_id: 1,
				purpose_of_visit_id: 1,
				is_finalize: null,
				status: 'open',
				is_approved: null,
				creation_source: 0,
				status_id: 1,
				is_active: 1,
				is_soft_registered: 0,
				case_insurances: [
					{
						id: 1,
						insurance_name: 'Zaid Insurance11111111',
						insurance_code: null,
						is_verified: null,
						created_by: null,
						updated_by: null,
						deleted_at: null,
						count: 3,
						pivot: {
							case_id: 170,
							insurance_id: 1,
							first_name: 'Mr',
							middle_name: 'Jacks',
							last_name: 'Smith',
							claim_no: 'Claim 1122 ',
							policy_no: '',
							wcb_no: 'G4521727',
							type: 'primary',
							insurance_location_id: 1,
							insurance_plan_name_id: 2,
						},
						checked: true,
						document_type_ids: [206],
					},
				],
				case_attorneys: [
					{
						id: 56,
						first_name: 'Mr',
						middle_name: 'Adeen',
						last_name: 'Willam',
						street_address: '334 Milford Street',
						suit_floor: '5th floor',
						city: 'Brooklyn',
						state: 'NY',
						zip: '11208',
						phone_no: '2222222222',
						ext: '33',
						cell_no: '3333333333',
						fax: '4444444444',
						email: 'william@test.com',
						comments: null,
						is_verified: 1,
						created_by: 1,
						updated_by: 1,
						created_at: '2020-08-04 13:01:22',
						updated_at: '2021-09-29 07:43:29',
						deleted_at: null,
						count: 479,
						pivot: {
							case_id: 170,
							attorney_id: 56,
						},
						document_type_ids: [207],
					},
				],
				case_employers: [
					{
						id: 123,
						employer_name: 'Test Employer',
						street_address: '334 West Grand Avenue',
						apartment_suite: '',
						city: 'Elmhurst',
						state: 'Illinois',
						zip: '60126',
						comments: null,
						email: '',
						phone_no: '3333333333',
						ext: '',
						fax: '',
						is_verified: 0,
						created_by: null,
						updated_by: null,
						created_at: '2020-06-17 16:02:02',
						updated_at: '2020-06-17 16:02:02',
						deleted_at: null,
						count: 0,
						pivot: {
							case_id: 170,
							employer_id: 123,
							occupation: 'Software Eng.',
							employer_type_id: 1,
						},
						checked: true,
						document_type_ids: [206],
					},
				],
				case_types: {
					id: 1,
					key: null,
					name: 'WC',
					slug: 'worker_compensation',
					description: 'Worker Compensation Insurance',
					comments: null,
					remainder_days: 30,
					created_by: 1,
					updated_by: 1,
				},
				patient: {
					id: 128,
					key: null,
					first_name: 'Mr',
					middle_name: 'Jacks',
					last_name: 'Smith',
					dob: '1993-03-04',
					gender: 'male',
					age: 28,
					ssn: '111111111',
					cell_phone: '2222222222',
					home_phone: '5555555555',
					work_phone: '',
					height_ft: 5,
					height_in: 4,
					weight_lbs: 120,
					weight_kg: null,
					meritial_status: 'single',
					profile_avatar: null,
					need_translator: 0,
					language: null,
					is_pregnant: null,
					is_law_enforcement_agent: null,
					status: 'open',
					notes: null,
					created_by: null,
					updated_by: null,
					created_at: '2020-06-17 15:37:50',
					updated_at: '2020-06-17 15:37:50',
					deleted_at: null,
					user_id: null,
					title: null,
					ethnicity: null,
					race: null,
					suffix: null,
					by_health_app: null,
					creation_source: 0,
					is_active: 1,
					is_soft_registered: 0,
					document_type_ids: [207],
				},
				accident_information: {
					id: 80,
					key: null,
					case_id: 170,
					accident_date: '2020-06-03',
					accident_time: null,
					patient_at_time_of_accident: 'passenger',
					at_time_of_accident_other_description: '',
					usual_work_location: null,
					location_reason: null,
					accident_location: null,
					accident_happend: 'erwrwe',
					street_no: '233 South 42nd Street',
					city: 'Kansas City',
					state: 'Kansas',
					zip: '66106',
					nature_of_accident: 'ewrwer',
					activity_at_injury: 'erwer',
					injury_description: 'erwer',
					injured_at_work_location: null,
					case_established: null,
					had_ime: null,
					apartment: null,
					driver_type: '',
					created_by: null,
					updated_by: null,
					created_at: '2020-06-17 16:01:09',
					updated_at: '2020-06-17 16:01:09',
					deleted_at: null,
					occupational_disease: null,
				},
			},
			speciality: {
				id: 2,
				name: 'Acupuncture',
				description: null,
				time_slot: 30,
				over_booking: 4,
				has_app: 1,
				speciality_key: 'accu',
				comments: null,
				default_name: 'ACCU',
				is_defualt: 1,
				is_available: 0,
				is_create_appointment: 1,
				created_by: 1,
				updated_by: 1,
				created_at: '2020-05-01 09:46:22',
				updated_at: '2021-06-15 08:49:06',
				deleted_at: null,
			},
		},
	];
	submitCreateBillFormVisitListWithOneCptFeeScheduleIDNull: any = [
		{
			id: 116,
			case_id: 170,
			patient_id: 128,
			doctor_id: 38,
			appointment_id: 129,
			speciality_id: 2,
			facility_location_id: 14,
			appointment_type_id: 2,
			visit_date: '2020-06-26 12:40:00',
			visit_session_state_id: 3,
			icd_codes_comment: null,
			cpt_codes_comment: null,
			visit_charges: '344.50',
			doctor_signature_id: null,
			patient_signature_id: null,
			is_amended: 0,
			is_tm_updatable: 0,
			document_uploaded: 1,
			last_uploaded_document_date: '2021-04-08 09:02:57',
			visit_date_format: '2020-06-26',
			no_of_days: 462,
			billing_title: 'MD',
			pivot: {
				bill_id: 389,
				visit_session_id: 116,
			},
			cpt_fee_schedules: [
				{
					id: null,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
				{
					id: 2313,
					base_price: '344.50',
					units: 4,
					per_unit_price: '86.13',
					total_charges: '344.50',
					visit_session_id: 116,
					code_id: 96114,
					fee_schedule_id: 5,
					created_by: null,
					updated_by: null,
					cpt_code: {
						id: 96114,
						name: 'Test Code 2224',
						type: 'CPT',
						code_type_id: 2,
						description: 'Test Code Description',
						short_description: null,
						medium_description: null,
						long_description: null,
						comments: 'Testing Comments Here',
						created_by: null,
						updated_by: null,
						deleted_at: null,
					},
					modifiers: [],
				},
			],
			appointment_type: {
				id: 2,
				name: 'FU',
				slug: 'follow_up',
				description: 'Test Comments124',
				created_by: null,
				updated_by: 1,
			},
			doctor: {
				id: 37,
				first_name: 'Mr',
				middle_name: 'Acu',
				last_name: 'Provider',
				user_id: 38,
			},
			facility_location: {
				id: 14,
				facility_id: 1,
				name: 'Test Location',
				city: 'Lahore',
				state: 'PW',
				zip: '54000',
				region_id: '1',
				address: '125 askari 9',
				phone: '1111111111',
				fax: '1111111111',
				email: 'test@mail.com',
				office_hours_start: null,
				office_hours_end: null,
				lat: 31.4681414,
				long: 74.4477643,
				day_list: '[0,1,2,3,4,5,6]',
				floor: '9/2A',
				place_of_service_id: 49,
				ext_no: null,
				cell_no: null,
				is_main: 0,
				same_as_provider: 0,
				created_by: 287,
				updated_by: 287,
				created_at: '2020-06-11 16:23:20',
				updated_at: '2021-08-26 08:15:21',
				deleted_at: null,
				facility_full_name: 'CitiMed - Test Location',
				facility: {
					id: 1,
					name: 'CitiMed',
					slug: 'citimed',
					created_by: 1,
					updated_by: 1,
				},
			},
			kiosk_case: {
				id: 170,
				key: null,
				patient_id: 128,
				case_type_id: 1,
				category_id: 1,
				purpose_of_visit_id: 1,
				is_finalize: null,
				status: 'open',
				is_approved: null,
				creation_source: 0,
				status_id: 1,
				is_active: 1,
				is_soft_registered: 0,
				case_insurances: [
					{
						id: 1,
						insurance_name: 'Zaid Insurance11111111',
						insurance_code: null,
						is_verified: null,
						created_by: null,
						updated_by: null,
						deleted_at: null,
						count: 3,
						pivot: {
							case_id: 170,
							insurance_id: 1,
							first_name: 'Mr',
							middle_name: 'Jacks',
							last_name: 'Smith',
							claim_no: 'Claim 1122 ',
							policy_no: '',
							wcb_no: 'G4521727',
							type: 'primary',
							insurance_location_id: 1,
							insurance_plan_name_id: 2,
						},
						checked: true,
						document_type_ids: [206],
					},
				],
				case_attorneys: [
					{
						id: 56,
						first_name: 'Mr',
						middle_name: 'Adeen',
						last_name: 'Willam',
						street_address: '334 Milford Street',
						suit_floor: '5th floor',
						city: 'Brooklyn',
						state: 'NY',
						zip: '11208',
						phone_no: '2222222222',
						ext: '33',
						cell_no: '3333333333',
						fax: '4444444444',
						email: 'william@test.com',
						comments: null,
						is_verified: 1,
						created_by: 1,
						updated_by: 1,
						created_at: '2020-08-04 13:01:22',
						updated_at: '2021-09-29 07:43:29',
						deleted_at: null,
						count: 479,
						pivot: {
							case_id: 170,
							attorney_id: 56,
						},
						document_type_ids: [207],
					},
				],
				case_employers: [
					{
						id: 123,
						employer_name: 'Test Employer',
						street_address: '334 West Grand Avenue',
						apartment_suite: '',
						city: 'Elmhurst',
						state: 'Illinois',
						zip: '60126',
						comments: null,
						email: '',
						phone_no: '3333333333',
						ext: '',
						fax: '',
						is_verified: 0,
						created_by: null,
						updated_by: null,
						created_at: '2020-06-17 16:02:02',
						updated_at: '2020-06-17 16:02:02',
						deleted_at: null,
						count: 0,
						pivot: {
							case_id: 170,
							employer_id: 123,
							occupation: 'Software Eng.',
							employer_type_id: 1,
						},
						checked: true,
						document_type_ids: [206],
					},
				],
				case_types: {
					id: 1,
					key: null,
					name: 'WC',
					slug: 'worker_compensation',
					description: 'Worker Compensation Insurance',
					comments: null,
					remainder_days: 30,
					created_by: 1,
					updated_by: 1,
				},
				patient: {
					id: 128,
					key: null,
					first_name: 'Mr',
					middle_name: 'Jacks',
					last_name: 'Smith',
					dob: '1993-03-04',
					gender: 'male',
					age: 28,
					ssn: '111111111',
					cell_phone: '2222222222',
					home_phone: '5555555555',
					work_phone: '',
					height_ft: 5,
					height_in: 4,
					weight_lbs: 120,
					weight_kg: null,
					meritial_status: 'single',
					profile_avatar: null,
					need_translator: 0,
					language: null,
					is_pregnant: null,
					is_law_enforcement_agent: null,
					status: 'open',
					notes: null,
					created_by: null,
					updated_by: null,
					created_at: '2020-06-17 15:37:50',
					updated_at: '2020-06-17 15:37:50',
					deleted_at: null,
					user_id: null,
					title: null,
					ethnicity: null,
					race: null,
					suffix: null,
					by_health_app: null,
					creation_source: 0,
					is_active: 1,
					is_soft_registered: 0,
					document_type_ids: [207],
				},
				accident_information: {
					id: 80,
					key: null,
					case_id: 170,
					accident_date: '2020-06-03',
					accident_time: null,
					patient_at_time_of_accident: 'passenger',
					at_time_of_accident_other_description: '',
					usual_work_location: null,
					location_reason: null,
					accident_location: null,
					accident_happend: 'erwrwe',
					street_no: '233 South 42nd Street',
					city: 'Kansas City',
					state: 'Kansas',
					zip: '66106',
					nature_of_accident: 'ewrwer',
					activity_at_injury: 'erwer',
					injury_description: 'erwer',
					injured_at_work_location: null,
					case_established: null,
					had_ime: null,
					apartment: null,
					driver_type: '',
					created_by: null,
					updated_by: null,
					created_at: '2020-06-17 16:01:09',
					updated_at: '2020-06-17 16:01:09',
					deleted_at: null,
					occupational_disease: null,
				},
			},
			speciality: {
				id: 2,
				name: 'Acupuncture',
				description: null,
				time_slot: 30,
				over_booking: 4,
				has_app: 1,
				speciality_key: 'accu',
				comments: null,
				default_name: 'ACCU',
				is_defualt: 1,
				is_available: 0,
				is_create_appointment: 1,
				created_by: 1,
				updated_by: 1,
				created_at: '2020-05-01 09:46:22',
				updated_at: '2021-06-15 08:49:06',
				deleted_at: null,
			},
		},
	];
	submitCreateBillFormVisitListWithEmptyCptFeeSchedule: any = [
		{
			id: 116,
			case_id: 170,
			patient_id: 128,
			doctor_id: 38,
			appointment_id: 129,
			speciality_id: 2,
			facility_location_id: 14,
			appointment_type_id: 2,
			visit_date: '2020-06-26 12:40:00',
			visit_session_state_id: 3,
			icd_codes_comment: null,
			cpt_codes_comment: null,
			visit_charges: '344.50',
			doctor_signature_id: null,
			patient_signature_id: null,
			is_amended: 0,
			is_tm_updatable: 0,
			document_uploaded: 1,
			last_uploaded_document_date: '2021-04-08 09:02:57',
			visit_date_format: '2020-06-26',
			no_of_days: 462,
			billing_title: 'MD',
			pivot: {
				bill_id: 389,
				visit_session_id: 116,
			},
			cpt_fee_schedules: [],
			appointment_type: {
				id: 2,
				name: 'FU',
				slug: 'follow_up',
				description: 'Test Comments124',
				created_by: null,
				updated_by: 1,
			},
			doctor: {
				id: 37,
				first_name: 'Mr',
				middle_name: 'Acu',
				last_name: 'Provider',
				user_id: 38,
			},
			facility_location: {
				id: 14,
				facility_id: 1,
				name: 'Test Location',
				city: 'Lahore',
				state: 'PW',
				zip: '54000',
				region_id: '1',
				address: '125 askari 9',
				phone: '1111111111',
				fax: '1111111111',
				email: 'test@mail.com',
				office_hours_start: null,
				office_hours_end: null,
				lat: 31.4681414,
				long: 74.4477643,
				day_list: '[0,1,2,3,4,5,6]',
				floor: '9/2A',
				place_of_service_id: 49,
				ext_no: null,
				cell_no: null,
				is_main: 0,
				same_as_provider: 0,
				created_by: 287,
				updated_by: 287,
				created_at: '2020-06-11 16:23:20',
				updated_at: '2021-08-26 08:15:21',
				deleted_at: null,
				facility_full_name: 'CitiMed - Test Location',
				facility: {
					id: 1,
					name: 'CitiMed',
					slug: 'citimed',
					created_by: 1,
					updated_by: 1,
				},
			},
			kiosk_case: {
				id: 170,
				key: null,
				patient_id: 128,
				case_type_id: 1,
				category_id: 1,
				purpose_of_visit_id: 1,
				is_finalize: null,
				status: 'open',
				is_approved: null,
				creation_source: 0,
				status_id: 1,
				is_active: 1,
				is_soft_registered: 0,
				case_insurances: [
					{
						id: 1,
						insurance_name: 'Zaid Insurance11111111',
						insurance_code: null,
						is_verified: null,
						created_by: null,
						updated_by: null,
						deleted_at: null,
						count: 3,
						pivot: {
							case_id: 170,
							insurance_id: 1,
							first_name: 'Mr',
							middle_name: 'Jacks',
							last_name: 'Smith',
							claim_no: 'Claim 1122 ',
							policy_no: '',
							wcb_no: 'G4521727',
							type: 'primary',
							insurance_location_id: 1,
							insurance_plan_name_id: 2,
						},
						checked: true,
						document_type_ids: [206],
					},
				],
				case_attorneys: [
					{
						id: 56,
						first_name: 'Mr',
						middle_name: 'Adeen',
						last_name: 'Willam',
						street_address: '334 Milford Street',
						suit_floor: '5th floor',
						city: 'Brooklyn',
						state: 'NY',
						zip: '11208',
						phone_no: '2222222222',
						ext: '33',
						cell_no: '3333333333',
						fax: '4444444444',
						email: 'william@test.com',
						comments: null,
						is_verified: 1,
						created_by: 1,
						updated_by: 1,
						created_at: '2020-08-04 13:01:22',
						updated_at: '2021-09-29 07:43:29',
						deleted_at: null,
						count: 479,
						pivot: {
							case_id: 170,
							attorney_id: 56,
						},
						document_type_ids: [207],
					},
				],
				case_employers: [
					{
						id: 123,
						employer_name: 'Test Employer',
						street_address: '334 West Grand Avenue',
						apartment_suite: '',
						city: 'Elmhurst',
						state: 'Illinois',
						zip: '60126',
						comments: null,
						email: '',
						phone_no: '3333333333',
						ext: '',
						fax: '',
						is_verified: 0,
						created_by: null,
						updated_by: null,
						created_at: '2020-06-17 16:02:02',
						updated_at: '2020-06-17 16:02:02',
						deleted_at: null,
						count: 0,
						pivot: {
							case_id: 170,
							employer_id: 123,
							occupation: 'Software Eng.',
							employer_type_id: 1,
						},
						checked: true,
						document_type_ids: [206],
					},
				],
				case_types: {
					id: 1,
					key: null,
					name: 'WC',
					slug: 'worker_compensation',
					description: 'Worker Compensation Insurance',
					comments: null,
					remainder_days: 30,
					created_by: 1,
					updated_by: 1,
				},
				patient: {
					id: 128,
					key: null,
					first_name: 'Mr',
					middle_name: 'Jacks',
					last_name: 'Smith',
					dob: '1993-03-04',
					gender: 'male',
					age: 28,
					ssn: '111111111',
					cell_phone: '2222222222',
					home_phone: '5555555555',
					work_phone: '',
					height_ft: 5,
					height_in: 4,
					weight_lbs: 120,
					weight_kg: null,
					meritial_status: 'single',
					profile_avatar: null,
					need_translator: 0,
					language: null,
					is_pregnant: null,
					is_law_enforcement_agent: null,
					status: 'open',
					notes: null,
					created_by: null,
					updated_by: null,
					created_at: '2020-06-17 15:37:50',
					updated_at: '2020-06-17 15:37:50',
					deleted_at: null,
					user_id: null,
					title: null,
					ethnicity: null,
					race: null,
					suffix: null,
					by_health_app: null,
					creation_source: 0,
					is_active: 1,
					is_soft_registered: 0,
					document_type_ids: [207],
				},
				accident_information: {
					id: 80,
					key: null,
					case_id: 170,
					accident_date: '2020-06-03',
					accident_time: null,
					patient_at_time_of_accident: 'passenger',
					at_time_of_accident_other_description: '',
					usual_work_location: null,
					location_reason: null,
					accident_location: null,
					accident_happend: 'erwrwe',
					street_no: '233 South 42nd Street',
					city: 'Kansas City',
					state: 'Kansas',
					zip: '66106',
					nature_of_accident: 'ewrwer',
					activity_at_injury: 'erwer',
					injury_description: 'erwer',
					injured_at_work_location: null,
					case_established: null,
					had_ime: null,
					apartment: null,
					driver_type: '',
					created_by: null,
					updated_by: null,
					created_at: '2020-06-17 16:01:09',
					updated_at: '2020-06-17 16:01:09',
					deleted_at: null,
					occupational_disease: null,
				},
			},
			speciality: {
				id: 2,
				name: 'Acupuncture',
				description: null,
				time_slot: 30,
				over_booking: 4,
				has_app: 1,
				speciality_key: 'accu',
				comments: null,
				default_name: 'ACCU',
				is_defualt: 1,
				is_available: 0,
				is_create_appointment: 1,
				created_by: 1,
				updated_by: 1,
				created_at: '2020-05-01 09:46:22',
				updated_at: '2021-06-15 08:49:06',
				deleted_at: null,
			},
		},
	];
}
