export const environment: { [task_mngr_api_dev: string]: any } = {
	production: true,
	isServer: false,
	host: 'http://localhost:4000',
	apiUrl: '',
	billing_api_url: 'https://billing.dev-sch.ovadamd.net/api/',
	fd_api_url: 'https://cm.dev-sch.ovadamd.net/api/',
	md_api_url: 'https://md.dev-sch.ovadamd.net/api/',
	schedulerApiUrl: 'https://cm.dev-sch.ovadamd.net/api/sch2',
	fd_api_url_vd: 'https://cm.dev-sch.ovadamd.net/api/vd/',
	schedulerApiUrl1: 'https://cm.dev-sch.ovadamd.net/api/sch2',
	health_app_api_url : ' https://health.dev-sch.ovadamd.net/api/',
	// schedulerApiUrl: "https://sch.dev-sch.ovadamd.org/",
	// schedulerApiUrl18: 'http://18.216.104.240:3000/',

	whitelistedDomains: ['localhost', '*.dev-sch.ovadamd.net'],
	// kiosk_api_path: 'https://192.168.1.194:5000/api/',
	kiosk_api_path: 'https://rk.dev-sch.ovadamd.net/api/',

	// kiosk_api_path: 'https://rk.dev-sch.ovadamd.org/api/',
	schedular_api_path: 'https://fd.dev-sch.ovadamd.net/api/',
	// document_mngr_api_path: 'https://dm.dev-sch.ovadamd.org/api/',
	document_mngr_api_path: 'https://cm.dev-sch.ovadamd.net/api/dm/',
	userManagementUrl: 'https://fd.dev-sch.ovadamd.net/api',
	billing_api_path: 'https://billing.dev-sch.ovadamd.net/api/',
	// task_mngr_api_dev: 'https://localhost:3000/api',
	task_mngr_api_dev: 'https://tm.dev-sch.ovadamd.net/api',
	gooleIncludedCountries: ['us', 'pk'],
  templateManagerUrl: 'https://templateapi.dev-sch.ovadamd.net/',
	// env for ringcentral
	RCSDK_VERSION: '3.2.2',
	username: 'qaiser.a@quickbillsmd.com',
	ext: '101',
	password: 'quickbills@123',
	appKey: 'tjxahW1YR7u0ATi_a037Vw',
	appSecret: 'jDbSyxalRT - idsNIO2 - fQQwXWVcTKdR2WBFqSuOkS83g',
	task_socketUrl: 'https://tm.dev-sch.ovadamd.net/',
	socketUrl: "https://socket.dev-sch.ovadamd.net/",

};
