export const environment: { [task_mngr_api_dev: string]: any } = {
    production: false,
    isServer: false,
    host: 'http://localhost:4000',
    apiUrl: "",
    billing_api_url: 'https://billing.ovadamd.org/api/',
    fd_api_url: "https://revampfd.ovadamd.org/api/",
    md_api_url: "https://md.ovadamd.org/api/",
    schedulerApiUrl: "https://cm.ovadamd.org/api/sch",
    // schedulerApiUrl18: 'http://18.216.104.240:3000/',
    whitelistedDomains: ["localhost", '*.ovadamd.org'],
    kiosk_api_path: 'https://cm.ovadamd.org/api/',
    schedular_api_path: 'https://sch.ovadamd.org/',
    document_mngr_api_path: 'https://dm.ovadamd.org/api/',
    userManagementUrl: 'https://fd.ovadamd.org/api',
    billing_api_path: 'https://billing.ovadamd.org/api/',
    task_mngr_api_dev: 'https://tm.ovadamd.org/api',
    gooleIncludedCountries: ['us', 'pk'],

    // env for ringcentral
    RCSDK_VERSION: '3.2.2',
    username: 'qaiser.a@quickbillsmd.com',
    ext: '101',
    password: 'quickbills@123',
    appKey: 'tjxahW1YR7u0ATi_a037Vw',
    appSecret: 'jDbSyxalRT - idsNIO2 - fQQwXWVcTKdR2WBFqSuOkS83g',
    task_socketUrl: "https://tm.ovadamd.org/",
};  