export class AutoGeneratedFolder{
    id: number;
    name: string;
    slug: string;
    description: string;
    parent_id: number;
    folder_type_id: number;
    show_files: boolean ;
    sub_folders: AutoGeneratedFolder[];
    facility_id:number
    speciality_id:number
    is_checked:boolean
    // "created_by"?: Date;
    // "updated_by"?: Date;
}
