// export const environment: { [name: string]: any } = {
//   production: false,
//   isServer: false,
//   host: 'https://www2.ovadamd.ml',
//   billing_api_url: 'https://billing.ovadamd.ml/api/',
//   apiUrl: "",
//   fd_api_url: "https://www2.ovadamd.ml/api/",
//   md_api_url: "https://www3.ovadamd.ml/ovada_cm_md_backend/api/",
//   schedulerApiUrl: "https://sch.ovadamd.ml/",
//   whitelistedDomains: ['54.157.104.184', '172.16.1.129', "localhost", 'https://staging.ovadamd.com'],
//   // kiosk_api_path: 'http://192.168.1.194:5000/api/',
//   kiosk_api_path: 'https://kb.ovadamd.ml/api/',
//   schedular_api_path: 'https://sch.ovadamd.ml/',
//   document_mngr_api_path: 'https://www3.ovadamd.ml/document-manager/api/',
//   userManagementUrl: 'https://www2.ovadamd.ml/api',
//   billing_api_path: 'https://billing.ovadamd.ml/api/',
//   // task_mngr_api_dev: 'http://localhost:3000/api',
//   task_mngr_api_dev: 'http://35.170.182.165:3000/api',
//   gooleIncludedCountries: ['us', 'pk'],
//   task_socketUrl: "http://35.170.182.165:3000/",
// };

// export const environment: { [name: string]: any } = {
//   production: false,
//   isServer: false,
//   host: 'https://www2.ovadamd.ml',
//   billing_api_url: 'https://billing.ovadamd.ml/api/',
//   apiUrl: "",
//   fd_api_url: "https://www2.ovadamd.ml/api/",
//   md_api_url: "https://www3.ovadamd.ml/ovada_cm_md_backend/api/",
//   schedulerApiUrl: "https://sch.ovadamd.ml/",
//   whitelistedDomains: ['54.157.104.184', '172.16.1.129', "localhost", 'staging.ovadamd.com', "www2.ovadamd.ml", "www3.ovadamd.ml", "kb.ovadamd.ml", "billing.ovadamd.ml"],
//   // kiosk_api_path: 'http://192.168.1.194:5000/api/',
//   kiosk_api_path: 'https://kb.ovadamd.ml/api/',
//   schedular_api_path: 'https://sch.ovadamd.ml/',
//   document_mngr_api_path: 'https://www3.ovadamd.ml/document-manager/api/',
//   userManagementUrl: 'https://www2.ovadamd.ml/api',
//   billing_api_path: 'https://billing.ovadamd.ml/api/',
//   // task_mngr_api_dev: 'http://localhost:3000/api',
//   task_mngr_api_dev: 'http://35.170.182.165:3000/api',
//   gooleIncludedCountries: ['us', 'pk'],
//   task_socketUrl: "http://35.170.182.165:3000/",
// };


export const environment: { [task_mngr_api_dev: string]: any } = {
  production: false,
  isServer: false,
  host: 'http://localhost:4000',
  apiUrl: "",
  billing_api_url: 'https://billing.ovadamd.net/api/',
  fd_api_url: "https://fd.ovadamd.net/api/",
  md_api_url: "https://md.ovadamd.net/api/",
  schedulerApiUrl: "https://cm.ovadamd.org/api/sch",
  // schedulerApiUrl18: 'http://18.216.104.240:3000/',
  whitelistedDomains: ["localhost", '*.ovadamd.net'],
  // kiosk_api_path: 'https://192.168.1.194:5000/api/',
  kiosk_api_path: 'https://kiosk.ovadamd.net/api/',
  // kiosk_api_path: 'https://cm.ovadamd.net/api/',
  schedular_api_path: 'https://sch.ovadamd.net/',
  document_mngr_api_path: 'https://dm.ovadamd.net/api/',
  userManagementUrl: 'https://fd.ovadamd.net/api',
  billing_api_path: 'https://billing.ovadamd.net/api/',
  // task_mngr_api_dev: 'https://localhost:3000/api',
  task_mngr_api_dev: 'https://tm.ovadamd.net/api',
  gooleIncludedCountries: ['us', 'pk'],

  // env for ringcentral
  RCSDK_VERSION: '3.2.2',
  username: 'qaiser.a@quickbillsmd.com',
  ext: '101',
  password: 'quickbills@123',
  appKey: 'tjxahW1YR7u0ATi_a037Vw',
  appSecret: 'jDbSyxalRT - idsNIO2 - fQQwXWVcTKdR2WBFqSuOkS83g',
  task_socketUrl: "https://tm.ovadamd.net/",
};