let data = [
    {
        actual_folder_name: "",
        added_by: null,
        child:
            [
                {
                    "id": 1875,
                    "object_id": 926,
                    "object_type": "patientCases",
                    "folder_name": "kiosk",
                    "actual_folder_name": "",
                    "folder_description": "",
                    "folder_path": "media/",
                    "parent": 1874,
                    "added_by": null,
                    "updated_by": null,
                    "created_at": "2020-04-25 13:06:31",
                    "updated_at": "2020-04-25 13:06:31",
                    "deleted_at": null,
                    "files_count": 3,
                    "total_files_count": 3,
                    "child": [],
                    "files": [
                        {
                            "id": 25956,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "authorizationToHIPAA",
                            "file_title": "Authorization For Release Of Health Information Pursuant To HIPAA",
                            "file_name": "1587821247_authorizationToHIPAA_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:27",
                            "updated_at": "2020-04-25 13:27:27",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 13,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25956"
                        },
                        {
                            "id": 25715,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "patientAwareness",
                            "file_title": "Patient HIPAA Awareness",
                            "file_name": "1587821246_patientAwareness_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:27",
                            "updated_at": "2020-04-25 13:27:27",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 6,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25715"
                        },
                        {
                            "id": 25712,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "intake",
                            "file_title": "Intake",
                            "file_name": "1587821245_intake_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:25",
                            "updated_at": "2020-04-25 13:27:25",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 7,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25712"
                        }
                    ]
                },
                {
                    "id": 21,
                    "object_id": 926,
                    "object_type": "patientCases",
                    "folder_name": "kiosk2",
                    "actual_folder_name": "",
                    "folder_description": "",
                    "folder_path": "media/",
                    "parent": 1874,
                    "added_by": null,
                    "updated_by": null,
                    "created_at": "2020-04-25 13:06:31",
                    "updated_at": "2020-04-25 13:06:31",
                    "deleted_at": null,
                    "files_count": 3,
                    "total_files_count": 3,
                    "child": [
                        {
                            "id": 22,
                            "object_id": 926,
                            "object_type": "patientCases",
                            "folder_name": "childers 1",
                            "actual_folder_name": "",
                            "folder_description": "",
                            "folder_path": "media/",
                            "parent": 1874,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:06:31",
                            "updated_at": "2020-04-25 13:06:31",
                            "deleted_at": null,
                            "files_count": 3,
                            "total_files_count": 3,
                            "child": [],
                            "files": [
                                {
                                    "id": 25956,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "authorizationToHIPAA",
                                    "file_title": "Authorization For Release Of Health Information Pursuant To HIPAA",
                                    "file_name": "1587821247_authorizationToHIPAA_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:27",
                                    "updated_at": "2020-04-25 13:27:27",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 13,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25956"
                                },
                                {
                                    "id": 25715,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "patientAwareness",
                                    "file_title": "Patient HIPAA Awareness",
                                    "file_name": "1587821246_patientAwareness_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:27",
                                    "updated_at": "2020-04-25 13:27:27",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 6,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25715"
                                },
                                {
                                    "id": 25712,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "intake",
                                    "file_title": "Intake",
                                    "file_name": "1587821245_intake_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:25",
                                    "updated_at": "2020-04-25 13:27:25",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 7,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25712"
                                }
                            ]
                        },
                        {
                            "id": 23,
                            "object_id": 926,
                            "object_type": "patientCases",
                            "folder_name": "child 2",
                            "actual_folder_name": "",
                            "folder_description": "",
                            "folder_path": "media/",
                            "parent": 1874,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:06:31",
                            "updated_at": "2020-04-25 13:06:31",
                            "deleted_at": null,
                            "files_count": 3,
                            "total_files_count": 3,
                            "child": [],
                            "files": [
                                {
                                    "id": 25718,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "authorizationToHIPAA",
                                    "file_title": "Authorization For Release Of Health Information Pursuant To HIPAA",
                                    "file_name": "1587821247_authorizationToHIPAA_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:27",
                                    "updated_at": "2020-04-25 13:27:27",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 13,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25718"
                                },
                                {
                                    "id": 25715,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "patientAwareness",
                                    "file_title": "Patient HIPAA Awareness",
                                    "file_name": "1587821246_patientAwareness_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:27",
                                    "updated_at": "2020-04-25 13:27:27",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 6,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25715"
                                },
                                {
                                    "id": 25712,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "intake",
                                    "file_title": "Intake",
                                    "file_name": "1587821245_intake_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:25",
                                    "updated_at": "2020-04-25 13:27:25",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 7,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25712"
                                }
                            ]
                        },
                    ],
                    "files": [
                        {
                            "id": 25718,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "authorizationToHIPAA",
                            "file_title": "Authorization For Release Of Health Information Pursuant To HIPAA",
                            "file_name": "1587821247_authorizationToHIPAA_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:27",
                            "updated_at": "2020-04-25 13:27:27",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 13,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25718"
                        },
                        {
                            "id": 25715,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "patientAwareness",
                            "file_title": "Patient HIPAA Awareness",
                            "file_name": "1587821246_patientAwareness_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:27",
                            "updated_at": "2020-04-25 13:27:27",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 6,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25715"
                        },
                        {
                            "id": 25712,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "intake",
                            "file_title": "Intake",
                            "file_name": "1587821245_intake_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:25",
                            "updated_at": "2020-04-25 13:27:25",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 7,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25712"
                        }
                    ]
                },
            ],
        files: [
            {
                "id": 25718,
                "folder_id": 1875,
                "reference_id": null,
                "reference_type": "authorizationToHIPAA",
                "file_title": "Authorization For Release Of Health Information Pursuant To HIPAA",
                "file_name": "1587821247_authorizationToHIPAA_926_citimed.pdf",
                "tags": null,
                "is_uploaded": 0,
                "added_by": null,
                "updated_by": null,
                "created_at": "2020-04-25 13:27:27",
                "updated_at": "2020-04-25 13:27:27",
                "deleted_at": null,
                "ext": "pdf",
                "reason_for_not_signed": null,
                "provider_id": 1,
                "case_id": 926,
                "document_type_id": 13,
                "batch": 867,
                "is_signed": null,
                "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25718"
            },
            {
                "id": 25715,
                "folder_id": 1875,
                "reference_id": null,
                "reference_type": "patientAwareness",
                "file_title": "Patient HIPAA Awareness",
                "file_name": "1587821246_patientAwareness_926_citimed.pdf",
                "tags": null,
                "is_uploaded": 0,
                "added_by": null,
                "updated_by": null,
                "created_at": "2020-04-25 13:27:27",
                "updated_at": "2020-04-25 13:27:27",
                "deleted_at": null,
                "ext": "pdf",
                "reason_for_not_signed": null,
                "provider_id": 1,
                "case_id": 926,
                "document_type_id": 6,
                "batch": 867,
                "is_signed": null,
                "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25715"
            },
            {
                "id": 25712,
                "folder_id": 1875,
                "reference_id": null,
                "reference_type": "intake",
                "file_title": "Intake",
                "file_name": "1587821245_intake_926_citimed.pdf",
                "tags": null,
                "is_uploaded": 0,
                "added_by": null,
                "updated_by": null,
                "created_at": "2020-04-25 13:27:25",
                "updated_at": "2020-04-25 13:27:25",
                "deleted_at": null,
                "ext": "pdf",
                "reason_for_not_signed": null,
                "provider_id": 1,
                "case_id": 926,
                "document_type_id": 7,
                "batch": 867,
                "is_signed": null,
                "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25712"
            }
        ],
        created_at: "2020-04-22 08:14:38",
        deleted_at: null,
        files_count: 3,
        folder_description: "",
        folder_name: "citimed",
        folder_path: "media/",
        id: 1857,
        object_id: 925,
        object_type: "patientCases",
        parent: null,
        total_files_count: 17,
        updated_at: "2020-04-22 08:14:38",
        updated_by: null
    },
    {
        actual_folder_name: "",
        added_by: null,
        created_at: "2020-04-22 08:14:38",
        deleted_at: null,
        files_count: 0,
        folder_description: "",
        folder_name: "optimum",
        folder_path: "media/",
        id: 1859,
        object_id: 925,
        object_type: "patientCases",
        parent: null,
        total_files_count: 14,
        updated_at: "2020-04-22 08:14:38",
        updated_by: null
    },
    {
        actual_folder_name: "",
        added_by: null,
        created_at: "2020-04-22 08:14:38",
        deleted_at: null,
        files_count: 0,
        folder_description: "",
        folder_name: "ims",
        folder_path: "media/",
        id: 1878,
        object_id: 925,
        object_type: "patientCases",
        parent: null,
        total_files_count: 13,
        updated_at: "2020-04-22 08:14:38",
        updated_by: null,
        child:
            [
                {
                    "id": 20,
                    "object_id": 926,
                    "object_type": "patientCases",
                    "folder_name": "imm main",
                    "actual_folder_name": "",
                    "folder_description": "",
                    "folder_path": "media/",
                    "parent": 1878,
                    "added_by": null,
                    "updated_by": null,
                    "created_at": "2020-04-25 13:06:31",
                    "updated_at": "2020-04-25 13:06:31",
                    "deleted_at": null,
                    "files_count": 3,
                    "total_files_count": 3,
                    "child": [],
                    "files": [
                        {
                            "id": 25718,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "authorizationToHIPAA",
                            "file_title": "Authorization For Release Of Health Information Pursuant To HIPAA",
                            "file_name": "1587821247_authorizationToHIPAA_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:27",
                            "updated_at": "2020-04-25 13:27:27",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 13,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25718"
                        },
                        {
                            "id": 25715,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "patientAwareness",
                            "file_title": "Patient HIPAA Awareness",
                            "file_name": "1587821246_patientAwareness_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:27",
                            "updated_at": "2020-04-25 13:27:27",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 6,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25715"
                        },
                        {
                            "id": 25712,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "intake",
                            "file_title": "Intake",
                            "file_name": "1587821245_intake_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:25",
                            "updated_at": "2020-04-25 13:27:25",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 7,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25712"
                        }
                    ]
                },
                {
                    "id": 21,
                    "object_id": 926,
                    "object_type": "patientCases",
                    "folder_name": "im main 2",
                    "actual_folder_name": "",
                    "folder_description": "",
                    "folder_path": "media/",
                    "parent": 1878,
                    "added_by": null,
                    "updated_by": null,
                    "created_at": "2020-04-25 13:06:31",
                    "updated_at": "2020-04-25 13:06:31",
                    "deleted_at": null,
                    "files_count": 3,
                    "total_files_count": 3,
                    "child": [
                        {
                            "id": 22,
                            "object_id": 926,
                            "object_type": "patientCases",
                            "folder_name": "childers 1",
                            "actual_folder_name": "",
                            "folder_description": "",
                            "folder_path": "media/",
                            "parent": 1878,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:06:31",
                            "updated_at": "2020-04-25 13:06:31",
                            "deleted_at": null,
                            "files_count": 3,
                            "total_files_count": 3,
                            "child": [],
                            "files": [
                                {
                                    "id": 25718,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "authorizationToHIPAA",
                                    "file_title": "Authorization For Release Of Health Information Pursuant To HIPAA",
                                    "file_name": "1587821247_authorizationToHIPAA_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:27",
                                    "updated_at": "2020-04-25 13:27:27",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 13,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25718"
                                },
                                {
                                    "id": 25715,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "patientAwareness",
                                    "file_title": "Patient HIPAA Awareness",
                                    "file_name": "1587821246_patientAwareness_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:27",
                                    "updated_at": "2020-04-25 13:27:27",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 6,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25715"
                                },
                                {
                                    "id": 25712,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "intake",
                                    "file_title": "Intake",
                                    "file_name": "1587821245_intake_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:25",
                                    "updated_at": "2020-04-25 13:27:25",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 7,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25712"
                                }
                            ]
                        },
                        {
                            "id": 23,
                            "object_id": 926,
                            "object_type": "patientCases",
                            "folder_name": "child 2",
                            "actual_folder_name": "",
                            "folder_description": "",
                            "folder_path": "media/",
                            "parent": 1878,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:06:31",
                            "updated_at": "2020-04-25 13:06:31",
                            "deleted_at": null,
                            "files_count": 3,
                            "total_files_count": 3,
                            "child": [],
                            "files": [
                                {
                                    "id": 25718,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "authorizationToHIPAA",
                                    "file_title": "Authorization For Release Of Health Information Pursuant To HIPAA",
                                    "file_name": "1587821247_authorizationToHIPAA_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:27",
                                    "updated_at": "2020-04-25 13:27:27",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 13,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25718"
                                },
                                {
                                    "id": 25715,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "patientAwareness",
                                    "file_title": "Patient HIPAA Awareness",
                                    "file_name": "1587821246_patientAwareness_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:27",
                                    "updated_at": "2020-04-25 13:27:27",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 6,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25715"
                                },
                                {
                                    "id": 25712,
                                    "folder_id": 1875,
                                    "reference_id": null,
                                    "reference_type": "intake",
                                    "file_title": "Intake",
                                    "file_name": "1587821245_intake_926_citimed.pdf",
                                    "tags": null,
                                    "is_uploaded": 0,
                                    "added_by": null,
                                    "updated_by": null,
                                    "created_at": "2020-04-25 13:27:25",
                                    "updated_at": "2020-04-25 13:27:25",
                                    "deleted_at": null,
                                    "ext": "pdf",
                                    "reason_for_not_signed": null,
                                    "provider_id": 1,
                                    "case_id": 926,
                                    "document_type_id": 7,
                                    "batch": 867,
                                    "is_signed": null,
                                    "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25712"
                                }
                            ]
                        },
                    ],
                    "files": [
                        {
                            "id": 25718,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "authorizationToHIPAA",
                            "file_title": "Authorization For Release Of Health Information Pursuant To HIPAA",
                            "file_name": "1587821247_authorizationToHIPAA_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:27",
                            "updated_at": "2020-04-25 13:27:27",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 13,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25718"
                        },
                        {
                            "id": 25715,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "patientAwareness",
                            "file_title": "Patient HIPAA Awareness",
                            "file_name": "1587821246_patientAwareness_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:27",
                            "updated_at": "2020-04-25 13:27:27",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 6,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25715"
                        },
                        {
                            "id": 25712,
                            "folder_id": 1875,
                            "reference_id": null,
                            "reference_type": "intake",
                            "file_title": "Intake",
                            "file_name": "1587821245_intake_926_citimed.pdf",
                            "tags": null,
                            "is_uploaded": 0,
                            "added_by": null,
                            "updated_by": null,
                            "created_at": "2020-04-25 13:27:25",
                            "updated_at": "2020-04-25 13:27:25",
                            "deleted_at": null,
                            "ext": "pdf",
                            "reason_for_not_signed": null,
                            "provider_id": 1,
                            "case_id": 926,
                            "document_type_id": 7,
                            "batch": 867,
                            "is_signed": null,
                            "link": "https://cm.ovadamd.org/api/dm/file-by-id?id=25712"
                        }
                    ]
                },
            ],
    }
]

export default data