export class dynamicFormMockValues {
	fields = [
		{
			allowed_case_type_slugs: [],
			onTypeahead$: {
				_isScalar: false,
				observers: [],
				closed: false,
				isStopped: false,
				hasError: false,
				thrownError: null,
			},
			element: 'div',
			children: [
				{
					allowed_case_type_slugs: [],
					onTypeahead$: {
						_isScalar: false,
						observers: [],
						closed: false,
						isStopped: false,
						hasError: false,
						thrownError: null,
					},
					element: 'div',
					children: [
						{
							allowed_case_type_slugs: [],
							onTypeahead$: {
								_isScalar: false,
								observers: [],
								closed: false,
								isStopped: false,
								hasError: false,
								thrownError: null,
							},
							element: 'div',
							children: [
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Chart ID',
									name: 'id',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-3'],
									configs: {
										mask: '000-00-0000',
										skip_validation: true,
									},
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Patient Name',
									name: 'name',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-3'],
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'DOB (mm/dd/yyyy)',
									name: 'dob',
									type: 'date',
									values: '',
									validations: [
										{
											name: 'max_date',
											message: 'Max date should be 8/25/2021',
										},
									],
									style: '',
									classes: ['col-sm-3'],
									configs: {
										max: '2021-08-25T08:31:52.879Z',
									},
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Primary Phone',
									name: 'phone_no',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-3'],
									configs: {
										mask: '000-000-0000',
										skip_validation: true,
									},
								},
							],
							classes: ['row'],
						},
					],
					classes: ['col-md-12 col-lg-12 col-xl-10'],
				},
				{
					allowed_case_type_slugs: [],
					onTypeahead$: {
						_isScalar: false,
						observers: [],
						closed: false,
						isStopped: false,
						hasError: false,
						thrownError: null,
					},
					element: 'div',
					children: [
						{
							allowed_case_type_slugs: [],
							onTypeahead$: {
								_isScalar: false,
								observers: [],
								closed: false,
								isStopped: false,
								hasError: false,
								thrownError: null,
							},
							element: 'div',
							children: [
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'button',
									label: 'Filter',
									classes: ['btn', 'btn-success w-100'],
									type: 'submit',
									configs: {
										button_classes: ['col-5 col-sm-3 col-lg-2 col-xl-6'],
									},
									onSubmit: null,
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'button',
									label: 'Reset',
									classes: ['btn', 'btn-primary w-100'],
									type: 'button',
									configs: {
										button_classes: ['col-5 col-sm-3 col-lg-2 col-xl-6'],
										disabled: true,
										name: 'resetBtn',
									},
								},
							],
							classes: ['row', 'justify-content-center'],
							values: '',
							style: '',
							configs: {
								name: 'button-div',
							},
						},
					],
					classes: ['col-md-12 col-lg-12 col-xl-2 mb-3 mb-xl-0'],
				},
			],
			classes: ['row', 'dynamic-filter'],
		},
	];
	disabledControlFiels = [
		{
			allowed_case_type_slugs: [],
			onTypeahead$: {
				_isScalar: false,
				observers: [],
				closed: false,
				isStopped: false,
				hasError: false,
				thrownError: null,
			},
			element: 'div',
			children: [
				{
					allowed_case_type_slugs: [],
					onTypeahead$: {
						_isScalar: false,
						observers: [],
						closed: false,
						isStopped: false,
						hasError: false,
						thrownError: null,
					},
					element: 'div',
					children: [
						{
							allowed_case_type_slugs: [],
							onTypeahead$: {
								_isScalar: false,
								observers: [],
								closed: false,
								isStopped: false,
								hasError: false,
								thrownError: null,
							},
							element: 'div',
							children: [
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Chart ID',
									name: 'id',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-3'],
									configs: {
										mask: '000-00-0000',
										skip_validation: true,
									},
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Patient Name',
									name: 'name',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-3'],
								},
								{
									allowed_case_type_slugs: [],
									form: true,
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'DOB (mm/dd/yyyy)',
									name: 'dob',
									type: 'date',
									values: '',
									validations: [
										{
											name: 'max_date',
											message: 'Max date should be 8/25/2021',
										},
									],
									style: '',
									classes: ['col-sm-3'],
									configs: {
										max: '2021-08-25T08:31:52.879Z',
									},
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Primary Phone',
									name: 'phone_no',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-3'],
									configs: {
										mask: '000-000-0000',
										skip_validation: true,
									},
								},
							],
							classes: ['row'],
						},
					],
					classes: ['col-md-12 col-lg-12 col-xl-10'],
				},
				{
					allowed_case_type_slugs: [],
					onTypeahead$: {
						_isScalar: false,
						observers: [],
						closed: false,
						isStopped: false,
						hasError: false,
						thrownError: null,
					},
					element: 'div',
					children: [
						{
							allowed_case_type_slugs: [],
							onTypeahead$: {
								_isScalar: false,
								observers: [],
								closed: false,
								isStopped: false,
								hasError: false,
								thrownError: null,
							},
							element: 'div',
							children: [
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'button',
									label: 'Filter',
									classes: ['btn', 'btn-success w-100'],
									type: 'submit',
									configs: {
										button_classes: ['col-5 col-sm-3 col-lg-2 col-xl-6'],
									},
									onSubmit: null,
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'button',
									label: 'Reset',
									classes: ['btn', 'btn-primary w-100'],
									type: 'button',
									configs: {
										button_classes: ['col-5 col-sm-3 col-lg-2 col-xl-6'],
										disabled: true,
										name: 'resetBtn',
									},
								},
							],
							classes: ['row', 'justify-content-center'],
							values: '',
							style: '',
							configs: {
								name: 'button-div',
							},
						},
					],
					classes: ['col-md-12 col-lg-12 col-xl-2 mb-3 mb-xl-0'],
				},
			],
			classes: ['row', 'dynamic-filter'],
		},
	];
	createChildControlsFields = [
		{
			allowed_case_type_slugs: [],
			onTypeahead$: {
				_isScalar: false,
				observers: [],
				closed: false,
				isStopped: false,
				hasError: false,
				thrownError: null,
			},
			element: 'div',
			children: [
				{
					allowed_case_type_slugs: [],
					onTypeahead$: {
						_isScalar: false,
						observers: [],
						closed: false,
						isStopped: false,
						hasError: false,
						thrownError: null,
					},
					element: 'div',
					children: [
						{
							allowed_case_type_slugs: [],
							onTypeahead$: {
								_isScalar: false,
								observers: [],
								closed: false,
								isStopped: false,
								hasError: false,
								thrownError: null,
							},
							element: 'div',
							children: [
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Chart ID',
									name: 'id',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-3'],
									configs: {
										mask: '000-00-0000',
										skip_validation: true,
										formControlName: 'nmae',
									},
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Patient Name',
									name: 'name',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-3'],
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'DOB (mm/dd/yyyy)',
									name: 'dob',
									type: 'date',
									values: '',
									validations: [
										{
											name: 'max_date',
											message: 'Max date should be 8/26/2021',
										},
									],
									style: '',
									classes: ['col-sm-3'],
									configs: {
										max: '2021-08-26T05:56:10.275Z',
									},
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'input',
									label: 'Primary Phone',
									name: 'phone_no',
									type: 'text',
									values: '',
									validations: [],
									style: '',
									classes: ['col-sm-3'],
									configs: {
										mask: '000-000-0000',
										skip_validation: true,
									},
								},
							],
							classes: ['row'],
						},
					],
					classes: ['col-md-12 col-lg-12 col-xl-10'],
				},
				{
					allowed_case_type_slugs: [],
					onTypeahead$: {
						_isScalar: false,
						observers: [],
						closed: false,
						isStopped: false,
						hasError: false,
						thrownError: null,
					},
					element: 'div',
					children: [
						{
							allowed_case_type_slugs: [],
							onTypeahead$: {
								_isScalar: false,
								observers: [],
								closed: false,
								isStopped: false,
								hasError: false,
								thrownError: null,
							},
							element: 'div',
							children: [
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'button',
									label: 'Filter',
									classes: ['btn', 'btn-success w-100'],
									type: 'submit',
									configs: {
										button_classes: ['col-5 col-sm-3 col-lg-2 col-xl-6'],
									},
									onSubmit: null,
								},
								{
									allowed_case_type_slugs: [],
									onTypeahead$: {
										_isScalar: false,
										observers: [],
										closed: false,
										isStopped: false,
										hasError: false,
										thrownError: null,
									},
									element: 'button',
									label: 'Reset',
									classes: ['btn', 'btn-primary w-100'],
									type: 'button',
									configs: {
										button_classes: ['col-5 col-sm-3 col-lg-2 col-xl-6'],
										disabled: true,
										name: 'resetBtn',
									},
								},
							],
							classes: ['row', 'justify-content-center'],
							values: '',
							style: '',
							configs: {
								name: 'button-div',
							},
						},
					],
					classes: ['col-md-12 col-lg-12 col-xl-2 mb-3 mb-xl-0'],
				},
			],
			classes: ['row', 'dynamic-filter'],
			configs: {
				formControlName: 'name',
			},
		},
	];
}
