/**
 * This is the dummy data for plan of care module testing. Import it in plan of care and
 * pass it in initialize form function instead of 'this.data'
 * Example
 * this.initializeForm(this.data);   //Replace this
 * this.initializeForm(planOfCareDebugData); //With this
 */
export const planOfCareDebugData = {
	radiologyOn: '1',
	radiologies: [
		{
			id: 1,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: ' INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 2,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: ' INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 3,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: ' INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 4,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: ' INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 5,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: 6,
			childChecked: true,
			otherComment: ' INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 7,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 8,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 9,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 10,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 11,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 12,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 13,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 14,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 15,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 16,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 17,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 18,
			left: true,
			right: true,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 19,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: ' INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 20,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: ' INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 21,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 22,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 23,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 24,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 25,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 26,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 27,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: null,
			sendPhysicianFilms: null,
		},
		{
			id: 28,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 29,
			left: false,
			right: false,
			heading: '',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
	],
	radiologyComments: 'INITIAL EVALUATION',
	CTScanOn: '1',
	ctScans: [
		{
			id: 1,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 2,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 3,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 4,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 5,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 6,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 7,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 8,
			left: true,
			right: true,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 9,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 10,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 11,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: 'with',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 12,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: true,
			sendPhysicianFilms: true,
		},
		{
			id: 13,
			left: false,
			right: false,
			heading: 'ctScans',
			withValue: '',
			childId: null,
			childChecked: false,
			otherComment: 'INITIAL EVALUATION',
			callStatReport: null,
			sendPhysicianFilms: null,
		},
	],
	ctComments: 'INITIAL EVALUATION',
	MRIOn: '1',
	MRI: [
		{
			id: 1,
			section: 'Brain/Head',
			name: 'Brain',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 2,
			section: 'Brain/Head',
			name: 'Pituitary',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 3,
			section: 'Brain/Head',
			name: 'IACs',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 4,
			section: 'Brain/Head',
			name: 'Orbits',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 5,
			section: 'Brain/Head',
			name: 'Sinuses',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 6,
			section: 'Brain/Head',
			name: 'TMJ',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: true,
			right: true,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 7,
			section: 'Brain/Head',
			name: 'Neck Soft Tissue',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 8,
			section: 'Spine',
			name: 'Cervical Spine',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 9,
			section: 'Spine',
			name: 'Thoracic Spine',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 10,
			section: 'Spine',
			name: 'Lumbar Spine',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 11,
			section: 'Body',
			name: 'Chest',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 12,
			section: 'Body',
			name: 'Abdomen',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 13,
			section: 'Body',
			name: 'Pelvis',
			parentId: 0,
			hasLeft: 0,
			hasRight: 0,
			with: 1,
			left: false,
			right: false,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 14,
			section: 'Extremities',
			name: 'Shoulder',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: true,
			right: true,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 15,
			section: 'Extremities',
			name: 'Elbow',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: true,
			right: true,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 16,
			section: 'Extremities',
			name: 'Wrist',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: true,
			right: true,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 17,
			section: 'Extremities',
			name: 'Hand',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: true,
			right: true,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 18,
			section: 'Extremities',
			name: 'Hip',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: true,
			right: true,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 19,
			section: 'Extremities',
			name: 'Knee',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: true,
			right: true,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 20,
			section: 'Extremities',
			name: 'Ankle',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: true,
			right: true,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 21,
			section: 'Extremities',
			name: 'Foot',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: true,
			right: true,
			callStatReport: true,
			sendPhysicianFilms: true,
			withValue: 'with',
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
		{
			id: 22,
			section: 'Extremities',
			name: 'Other',
			parentId: 0,
			hasLeft: 1,
			hasRight: 1,
			with: 1,
			left: false,
			right: false,
			callStatReport: null,
			sendPhysicianFilms: null,
			withValue: null,
			checked: true,
			otherComment: 'INITIAL EVALUATION',
		},
	],
	mriComments: 'INITIAL EVALUATION',
	otherOn: '1',
	others: {
		other: [],
		mrAngiographies: [
			{
				id: 1,
				left: false,
				right: false,
				heading: 'mrAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 2,
				left: false,
				right: false,
				heading: 'mrAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 3,
				left: false,
				right: false,
				heading: 'mrAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 4,
				left: false,
				right: false,
				heading: 'mrAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 5,
				left: false,
				right: false,
				heading: 'mrAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 6,
				left: false,
				right: false,
				heading: 'mrAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 7,
				left: false,
				right: false,
				heading: 'mrAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 8,
				left: false,
				right: false,
				heading: 'mrAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 9,
				left: false,
				right: false,
				heading: 'mrAngiographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: null,
				sendPhysicianFilms: null,
			},
		],
		ctaAngiographies: [
			{
				id: 1,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 2,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 3,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 4,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 5,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 6,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 7,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 8,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 9,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: 'with',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 10,
				left: false,
				right: false,
				heading: 'ctaAngiographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: null,
				sendPhysicianFilms: null,
			},
		],
		mammographies: [
			{
				id: 1,
				left: false,
				right: false,
				heading: 'mammographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 2,
				left: false,
				right: false,
				heading: 'mammographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 3,
				left: false,
				right: false,
				heading: 'mammographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 4,
				left: false,
				right: false,
				heading: 'mammographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 5,
				left: false,
				right: false,
				heading: 'mammographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 6,
				left: false,
				right: false,
				heading: 'mammographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 7,
				left: false,
				right: false,
				heading: 'mammographies',
				withValue: '',
				childId: 8,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 9,
				left: false,
				right: false,
				heading: 'mammographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 10,
				left: false,
				right: false,
				heading: 'mammographies',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
		],
		ultrasounds: [
			{
				id: 1,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 2,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 3,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 4,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 5,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 6,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: 7,
				childChecked: true,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 8,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 9,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 10,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 11,
				left: false,
				right: false,
				heading: 'ultrasounds',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: null,
				sendPhysicianFilms: null,
			},
		],
		dexa: [
			{
				id: 1,
				left: false,
				right: false,
				heading: 'dexa',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
			{
				id: 2,
				left: false,
				right: false,
				heading: 'dexa',
				withValue: '',
				childId: null,
				childChecked: false,
				otherComment: 'INITIAL EVALUATION',
				callStatReport: true,
				sendPhysicianFilms: true,
			},
		],
	},
	otherComments: 'INITIAL EVALUATION',
	devices: [
		{
			id: 1,
			name: 'Lumbar cushion',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 2,
			name: 'Knee Brace',
			location: true,
			selected_location: 'both',
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 3,
			name: 'Cervical pillow',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 4,
			name: 'LSO',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 5,
			name: 'Wrist Brace',
			location: true,
			selected_location: 'both',
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 6,
			name: 'Cervical collar',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 7,
			name: 'Elbow Brace',
			location: true,
			selected_location: 'both',
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 8,
			name: 'Ankle Brace',
			location: true,
			selected_location: 'both',
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 9,
			name: 'Hot/cold pack',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 10,
			name: 'Cane',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 11,
			name: 'Ultrasound unit',
			location: false,
			selected_location: null,
			length_of_need: {
				seededLengths: [28, 42, 56, 'other'],
				length: 'other',
				other_comment: 'INITIAL EVALUATION',
			},
			usage: {
				seeded_usage: ['use_in_control_unit', 'time', 'hour'],
				use_in_control_unit: true,
				settings: true,
				frequency: '',
				pressure: '',
				time: 3,
			},
			seeded_body_part_ids: [
				{
					id: 38,
					name: 'Cervical Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 39,
					name: 'Thoracic Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 40,
					name: 'Lumbar Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 41,
					name: 'Shoulder',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 42,
					name: 'Elbow',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 43,
					name: 'Hand/Wrist',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 44,
					name: 'Hip/Groin',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 45,
					name: 'Knee',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 46,
					name: 'Ankle',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
			],
			seeded_body_parts: [
				{
					id: 38,
					name: 'Cervical Spine',
					bodyPartKey: null,
					type: 'ultrasound',
					has_comments: 0,
					hasLocation: false,
				},
				{
					id: 39,
					name: 'Thoracic Spine',
					bodyPartKey: null,
					type: 'ultrasound',
					has_comments: 0,
					hasLocation: false,
				},
				{
					id: 40,
					name: 'Lumbar Spine',
					bodyPartKey: null,
					type: 'ultrasound',
					has_comments: 0,
					hasLocation: false,
				},
				{
					id: 41,
					name: 'Shoulder',
					bodyPartKey: null,
					type: 'ultrasound',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 42,
					name: 'Elbow',
					bodyPartKey: null,
					type: 'ultrasound',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 43,
					name: 'Hand/Wrist',
					bodyPartKey: null,
					type: 'ultrasound',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 44,
					name: 'Hip/Groin',
					bodyPartKey: null,
					type: 'ultrasound',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 45,
					name: 'Knee',
					bodyPartKey: null,
					type: 'ultrasound',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 46,
					name: 'Ankle',
					bodyPartKey: null,
					type: 'ultrasound',
					has_comments: 0,
					hasLocation: true,
				},
			],
			body_parts: [
				{
					id: 38,
					name: 'Cervical Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 39,
					name: 'Thoracic Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 40,
					name: 'Lumbar Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 41,
					name: 'Shoulder',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 42,
					name: 'Elbow',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 43,
					name: 'Hand/Wrist',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 44,
					name: 'Hip/Groin',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 45,
					name: 'Knee',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 46,
					name: 'Ankle',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
			],
			comments: '',
			checked: true,
		},
		{
			id: 12,
			name: 'Cervical Traction',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 13,
			name: 'Intermittent Cold Therapy',
			location: false,
			selected_location: null,
			length_of_need: {
				seededLengths: [14, 21, 28, 'other'],
				length: 'other',
				other_comment: 'INITIAL EVALUATION',
			},
			usage: {
				seeded_usage: ['use_in_control_unit', 'frequency', 'pressure', 'time', 'minutes'],
				use_in_control_unit: true,
				settings: true,
				frequency: 2,
				pressure: 'no',
				time: 2,
			},
			seeded_body_part_ids: [
				{
					id: 47,
					name: 'Cervical Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 48,
					name: 'Thoracic Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 49,
					name: 'Lumbar Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 50,
					name: 'Shoulder',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 51,
					name: 'Elbow',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'right',
					comments: null,
				},
				{
					id: 52,
					name: 'Hand/Wrist',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 53,
					name: 'Hip/Groin',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'right',
					comments: null,
				},
				{
					id: 54,
					name: 'Knee',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 55,
					name: 'Ankle',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'right',
					comments: null,
				},
			],
			seeded_body_parts: [
				{
					id: 47,
					name: 'Cervical Spine',
					bodyPartKey: null,
					type: 'coldTharapy',
					has_comments: 0,
					hasLocation: false,
				},
				{
					id: 48,
					name: 'Thoracic Spine',
					bodyPartKey: null,
					type: 'coldTharapy',
					has_comments: 0,
					hasLocation: false,
				},
				{
					id: 49,
					name: 'Lumbar Spine',
					bodyPartKey: null,
					type: 'coldTharapy',
					has_comments: 0,
					hasLocation: false,
				},
				{
					id: 50,
					name: 'Shoulder',
					bodyPartKey: null,
					type: 'coldTharapy',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 51,
					name: 'Elbow',
					bodyPartKey: null,
					type: 'coldTharapy',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 52,
					name: 'Hand/Wrist',
					bodyPartKey: null,
					type: 'coldTharapy',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 53,
					name: 'Hip/Groin',
					bodyPartKey: null,
					type: 'coldTharapy',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 54,
					name: 'Knee',
					bodyPartKey: null,
					type: 'coldTharapy',
					has_comments: 0,
					hasLocation: true,
				},
				{
					id: 55,
					name: 'Ankle',
					bodyPartKey: null,
					type: 'coldTharapy',
					has_comments: 0,
					hasLocation: true,
				},
			],
			body_parts: [
				{
					id: 47,
					name: 'Cervical Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 48,
					name: 'Thoracic Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 49,
					name: 'Lumbar Spine',
					hasLocation: false,
					has_comments: false,
					body_part_id: null,
					location: null,
					comments: null,
				},
				{
					id: 50,
					name: 'Shoulder',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 51,
					name: 'Elbow',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'right',
					comments: null,
				},
				{
					id: 52,
					name: 'Hand/Wrist',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 53,
					name: 'Hip/Groin',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'right',
					comments: null,
				},
				{
					id: 54,
					name: 'Knee',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'left',
					comments: null,
				},
				{
					id: 55,
					name: 'Ankle',
					hasLocation: true,
					has_comments: false,
					body_part_id: null,
					location: 'right',
					comments: null,
				},
			],
			comments: '',
			checked: true,
		},
		{
			id: 14,
			name: 'TLSO',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 15,
			name: 'Tens Unit',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 16,
			name: 'Ergonomic pillow',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 17,
			name: 'Shoulder brace with abduction',
			location: true,
			selected_location: 'both',
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 18,
			name: 'Shoulder Sling',
			location: true,
			selected_location: 'both',
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 19,
			name: 'Cam both',
			location: true,
			selected_location: 'both',
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 20,
			name: 'Massager',
			location: false,
			selected_location: null,
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
		{
			id: 21,
			name: 'Other',
			location: true,
			selected_location: 'both',
			length_of_need: null,
			usage: null,
			seeded_body_part_ids: [],
			seeded_body_parts: null,
			body_parts: [],
			comments: 'INITIAL EVALUATION',
			checked: true,
		},
	],
	followUpVisit: 'a week',
	followUpOther: '',
	orthopedic: 'INITIAL EVALUATION',
	orthopedic_checked: true,
	painManagement: 'INITIAL EVALUATION',
	painManagement_checked: true,
	pmr: 'INITIAL EVALUATION',
	pmr_checked: true,
	spineSpecialist: 'INITIAL EVALUATION',
	spineSpecialist_checked: true,
	handSpecialist: 'INITIAL EVALUATION',
	handSpecialist_checked: true,
	podiatry: 'INITIAL EVALUATION',
	podiatry_checked: true,
	neurology: 'INITIAL EVALUATION',
	neurology_checked: true,
	extremities: 'upper extremities',
	other: 'INITIAL EVALUATION',
	other_checked: true,
	comment: 'INITIAL EVALUATION',
	casualityComments: 'INITIAL EVALUATION',
	temporarilyImpairedComment: 'INITIAL EVALUATION',
	temporarilyImpaired: 2,
	medications: {
		useOld: true,
		newDrugs: 'INITIAL EVALUATION',
		usePrescribed: true,
		prescribedDrugs: 'INITIAL EVALUATION',
		workEffect: true,
	},
	prognosisCheck: true,
	prognosis: '',
	specialities: [
		{
			id: 1,
			name: 'ALLERGY & IMMUNOLOGY',
			checked: false,
			dropped: false,
			comment: '',
			children: null,
		},
		{
			id: 2,
			name: 'ANESTHESIOLOGY',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 3,
					name: 'Critical care medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 4,
					name: 'Hospice and palliative care',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 5,
					name: 'Pain medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 6,
					name: 'Pediatric anesthesiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 7,
					name: 'Sleep medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 8,
			name: 'DERMATOLOGY',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 9,
					name: 'Dermatopathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 10,
					name: 'Pediatric dermatology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 11,
			name: 'DIAGNOSTIC RADIOLOGY',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 12,
					name: 'Abdominal radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 13,
					name: 'Breast imaging',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 14,
					name: 'Cardiothoracic radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 15,
					name: 'Cardiovascular radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 16,
					name: 'Chest radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 17,
					name: 'Emergency radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 18,
					name: 'Endovascular surgical neuroradiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 19,
					name: 'Gastrointestinal radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 20,
					name: 'Genitourinary radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 21,
					name: 'Head and neck radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 22,
					name: 'Interventional radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 23,
					name: 'Musculoskeletal radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 24,
					name: 'Neuroradiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 25,
					name: 'Nuclear radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 26,
					name: 'Pediatric radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 27,
					name: 'Radiation oncology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 28,
					name: 'Vascular and interventional radiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 29,
			name: 'EMERGENCY MEDICINE',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 30,
					name: 'Anesthesiology critical care medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 31,
					name: 'Emergency medical services',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 32,
					name: 'Hospice and palliative medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 33,
					name: 'Internal medicine / Critical care medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 34,
					name: 'Medical toxicology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 35,
					name: 'Pediatric emergency medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 36,
					name: 'Sports medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 37,
					name: 'Undersea and hyperbaric medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 38,
			name: 'FAMILY MEDICINE',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 39,
					name: 'Adolescent medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 40,
					name: 'Geriatric medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 41,
			name: 'INTERNAL MEDICINE',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 42,
					name: 'Advanced heart failure and transplant cardiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 43,
					name: 'Cardiovascular disease',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 44,
					name: 'Clinical cardiac electrophysiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 45,
					name: 'Endocrinology diabetes, and metabolism',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 46,
					name: 'Gastroenterology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{ id: 47, name: 'Hematology', checked: false, dropped: false, comment: '', children: null },
				{
					id: 48,
					name: 'Hematology and oncology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 49,
					name: 'Interventional cardiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{ id: 50, name: 'Nephrology', checked: false, dropped: false, comment: '', children: null },
				{ id: 51, name: 'Oncology', checked: false, dropped: false, comment: '', children: null },
				{
					id: 52,
					name: 'Pulmonary disease and critical care medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 53,
					name: 'Rheumatology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 54,
					name: 'Transplant hepatology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 55,
			name: 'MEDICAL GENETICS',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 56,
					name: 'Biochemical genetics',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 57,
					name: 'Clinical cytogenetics',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 58,
					name: 'Clinical genetics',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 59,
					name: 'Molecular genetic pathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 60,
			name: 'NEUROLOGY',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 61,
					name: 'Brain injury medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 62,
					name: 'Child neurology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 63,
					name: 'Clinical neurophysiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 64,
					name: 'Neurodevelopmental disabilities',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 65,
					name: 'Neuromuscular medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 66,
					name: 'Vascular neurology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 67,
			name: 'NUCLEAR MEDICINE',
			checked: false,
			dropped: false,
			comment: '',
			children: null,
		},
		{
			id: 68,
			name: 'OBSTETRICS AND GYNECOLOGY',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 69,
					name: 'Female pelvic medicine and reconstructive surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 70,
					name: 'Gynecologic oncology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 71,
					name: 'Maternal-fetal medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 72,
					name: 'Reproductive endocrinologists and infertility',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 73,
			name: 'OPHTHALMOLOGY',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 74,
					name: 'Anterior segment/cornea ophthalmology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 75,
					name: 'Glaucoma ophthalmology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 76,
					name: 'Neuro-ophthalmology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 77,
					name: 'Ocular oncology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 78,
					name: 'Oculoplastics/orbit',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 79,
					name: 'Ophthalmic Plastic & Reconstructive Surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 80,
					name: 'Retina/uveitis',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 81,
					name: 'Strabismus/pediatric ophthalmology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 82,
			name: 'PATHOLOGY',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 83,
					name: 'Anatomical pathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 84,
					name: 'Blood banking and transfusion medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 85,
					name: 'Chemical pathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 86,
					name: 'Clinical pathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 87,
					name: 'Cytopathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 88,
					name: 'Forensic pathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 89,
					name: 'Genetic pathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 90,
					name: 'Immunopathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 91,
					name: 'Medical microbiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 92,
					name: 'Molecular pathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 93,
					name: 'Neuropathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 94,
					name: 'Pediatric pathology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 95,
			name: 'PEDIATRICS',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 96,
					name: 'Child abuse pediatrics',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 97,
					name: 'Developmental-behavioral pediatrics',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 98,
					name: 'Neonatal-perinatal medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 99,
					name: 'Pediatric cardiology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 100,
					name: 'Pediatric critical care medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 101,
					name: 'Pediatric endocrinology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 102,
					name: 'Pediatric gastroenterology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 103,
					name: 'Pediatric hematology-oncology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 104,
					name: 'Pediatric infectious diseases',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 105,
					name: 'Pediatric nephrology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 106,
					name: 'Pediatric pulmonology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 107,
					name: 'Pediatric rheumatology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 108,
					name: 'Pediatric sports medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 109,
					name: 'Pediatric transplant hepatology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 110,
			name: 'PHYSICAL MEDICINE & REHABILITATION',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 111,
					name: 'Pediatric rehabilitation medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 112,
					name: 'Spinal cord injury medicine',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 113,
			name: 'PREVENTIVE MEDICINE',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 114,
					name: 'Addiction psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 115,
					name: 'Administrative psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 116,
					name: 'Child and adolescent psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 117,
					name: 'Community psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 118,
					name: 'Consultation/liaison psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 119,
					name: 'Emergency psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 120,
					name: 'Forensic psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 121,
					name: 'Geriatric psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 122,
					name: 'Mental retardation psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 123,
					name: 'Military psychiatry',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 124,
					name: 'Psychiatric research',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 125,
			name: 'SURGERY',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 126,
					name: 'Colon and rectal surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 127,
					name: 'General surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: [
						{
							id: 128,
							name: 'Surgical critical care',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
					],
				},
				{
					id: 129,
					name: 'Plastic surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: [
						{
							id: 130,
							name: 'Craniofacial surgery',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 131,
							name: 'Hand surgery',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
					],
				},
				{
					id: 132,
					name: 'Neurological surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 133,
					name: 'Ophthalmic surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 134,
					name: 'Oral and maxillofacial surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 135,
					name: 'Orthopaedic surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: [
						{
							id: 136,
							name: 'Adult reconstructive orthopaedics',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 137,
							name: 'Foot and ankle orthopaedics',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 138,
							name: 'Musculoskeletal oncology',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 139,
							name: 'Orthopaedic sports medicine',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 140,
							name: 'Orthopaedic surgery of the spine',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 141,
							name: 'Orthopaedic trauma',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 142,
							name: 'Pediatric orthopaedics',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
					],
				},
				{
					id: 143,
					name: 'Otolaryngology',
					checked: false,
					dropped: false,
					comment: '',
					children: [
						{
							id: 144,
							name: 'Pediatric otolaryngology',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
					],
				},
				{
					id: 145,
					name: 'Otology neurotology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 146,
					name: 'Pediatric surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: [
						{
							id: 147,
							name: 'Neonatal',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 148,
							name: 'Prenatal',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 149,
							name: 'Trauma',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 150,
							name: 'Pediatric oncology',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
					],
				},
				{
					id: 151,
					name: 'Thoracic Surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: [
						{
							id: 152,
							name: 'Congenital cardiac surgery',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
						{
							id: 153,
							name: 'Thoracic surgery-integrated',
							checked: false,
							dropped: false,
							comment: '',
							children: null,
						},
					],
				},
				{
					id: 154,
					name: 'Vascular surgery',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
		{
			id: 155,
			name: 'UROLOGY',
			checked: false,
			dropped: false,
			comment: '',
			children: [
				{
					id: 156,
					name: 'Pediatric urology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 157,
					name: 'Urologic oncology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 158,
					name: 'Renal transplant',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 159,
					name: 'Male infertility',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{ id: 160, name: 'Calculi', checked: false, dropped: false, comment: '', children: null },
				{
					id: 161,
					name: 'Female urology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
				{
					id: 162,
					name: 'Neurourology',
					checked: false,
					dropped: false,
					comment: '',
					children: null,
				},
			],
		},
	],
	referrals: [
		{
			id: 1,
			specialty: 'Physical Therapy',
			checked: true,
			perWeek: '3',
			periodName: 'month',
			intervalName: 'week',
			noOfWeeks: '2',
			improvement: '',
			comment:
				'At this time will enroll the patient in a course of Physical Therapy 3x/week for 2 months to decrease pain, increase strength and range of motion with modalities as needed. INITIAL EVALUATION',
			diagnosis: [45, 46, 47],
			precautions: 'INITIAL EVALUATION',
			evaluate: 'INITIAL EVALUATION',
			specificInstructions: 'INITIAL EVALUATION',
			weightBearings: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
			],
			exercises: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
				{ id: 6, checked: true },
				{ id: 7, checked: true },
				{ id: 8, checked: true },
				{ id: 9, checked: true },
				{ id: 10, checked: true },
				{ id: 11, checked: true },
				{ id: 12, checked: true },
				{ id: 13, checked: true },
				{ id: 14, checked: true },
				{ id: 15, checked: true },
				{ id: 16, checked: true },
				{ id: 17, checked: true },
				{ id: 18, checked: true },
				{ id: 19, checked: true },
				{ id: 20, checked: true },
				{ id: 21, checked: true },
				{ id: 22, checked: true },
				{ id: 23, checked: true },
				{ id: 24, checked: true },
				{ id: 25, checked: true },
			],
			modalities: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
				{ id: 6, checked: true },
				{ id: 7, checked: true },
				{ id: 8, checked: true },
				{ id: 9, checked: true },
				{ id: 10, checked: true },
			],
			goals: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
			],
			tharapies: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
			],
		},
		{
			id: 2,
			specialty: 'Occupational',
			checked: true,
			perWeek: 1,
			periodName: 'week',
			intervalName: 'week',
			noOfWeeks: 1,
			improvement: '',
			comment:
				'At this time will enroll the patient in a course of Occupational 1x/week for 1 week to decrease pain, increase strength and range of motion with modalities as needed. INITIAL EVALUATION',
			diagnosis: [45, 46, 47],
			precautions: 'INITIAL EVALUATION',
			evaluate: 'INITIAL EVALUATION',
			specificInstructions: 'INITIAL EVALUATION',
			weightBearings: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
			],
			exercises: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
				{ id: 6, checked: true },
				{ id: 7, checked: true },
				{ id: 8, checked: true },
				{ id: 9, checked: true },
				{ id: 10, checked: true },
				{ id: 11, checked: true },
				{ id: 12, checked: true },
				{ id: 13, checked: true },
				{ id: 14, checked: true },
				{ id: 15, checked: true },
				{ id: 16, checked: true },
				{ id: 17, checked: true },
				{ id: 18, checked: true },
				{ id: 19, checked: true },
				{ id: 20, checked: true },
				{ id: 21, checked: true },
				{ id: 22, checked: true },
				{ id: 23, checked: true },
				{ id: 24, checked: true },
				{ id: 25, checked: true },
			],
			modalities: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
				{ id: 6, checked: true },
				{ id: 7, checked: true },
				{ id: 8, checked: true },
				{ id: 9, checked: true },
				{ id: 10, checked: true },
			],
			goals: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
			],
			tharapies: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
			],
		},
		{
			id: 3,
			specialty: 'Chiropractor',
			checked: true,
			perWeek: 3,
			periodName: 'week',
			intervalName: 'week',
			noOfWeeks: 2,
			improvement: '',
			comment:
				'At this time will enroll the patient in a course of Chiropractor 3x/week for 2 weeks to decrease pain, increase strength and range of motion with modalities as needed. INITIAL EVALUATION',
			diagnosis: [45, 46, 47],
			precautions: 'INITIAL EVALUATION',
			evaluate: 'INITIAL EVALUATION',
			specificInstructions: 'INITIAL EVALUATION',
			weightBearings: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
			],
			exercises: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
				{ id: 6, checked: true },
				{ id: 7, checked: true },
				{ id: 8, checked: true },
				{ id: 9, checked: true },
				{ id: 10, checked: true },
				{ id: 11, checked: true },
				{ id: 12, checked: true },
				{ id: 13, checked: true },
				{ id: 14, checked: true },
				{ id: 15, checked: true },
				{ id: 16, checked: true },
				{ id: 17, checked: true },
				{ id: 18, checked: true },
				{ id: 19, checked: true },
				{ id: 20, checked: true },
				{ id: 21, checked: true },
				{ id: 22, checked: true },
				{ id: 23, checked: true },
				{ id: 24, checked: true },
				{ id: 25, checked: true },
			],
			modalities: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
				{ id: 6, checked: true },
				{ id: 7, checked: true },
				{ id: 8, checked: true },
				{ id: 9, checked: true },
				{ id: 10, checked: true },
			],
			goals: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
			],
			tharapies: [
				{ id: 1, checked: true },
				{ id: 2, checked: true },
				{ id: 3, checked: true },
				{ id: 4, checked: true },
				{ id: 5, checked: true },
			],
		},
	],
	hbotPrescription: true,
	synapticTreatment: true,
	rangeOfMotion: true,
	orientedBodyParts: [
		{ name: 'Shoulder', bodyPartId: 30, checked: true, orientation: 'left' },
		{ name: 'Elbow', bodyPartId: 31, checked: true, orientation: 'left' },
		{ name: 'Wrist', bodyPartId: 33, checked: true, orientation: 'left' },
		{ name: 'Hip', bodyPartId: 34, checked: true, orientation: 'left' },
		{ name: 'Knee', bodyPartId: 36, checked: true, orientation: 'left' },
		{ name: 'Ankle', bodyPartId: 37, checked: true, orientation: 'left' },
	],
	nonOrientedBodyParts: [
		{ name: 'Cervical Spine', bodyPartId: 29, checked: true },
		{ name: 'Thoracic Spine', bodyPartId: 32, checked: true },
		{ name: 'Lumbar Spine', bodyPartId: 35, checked: true },
	],
};
