export class patientFormMockValues {
	getPatientResponce = {
		message: 'success',
		status: 200,
		result: {
			data: [
				{
					creation_source_string: 'Web',
					id: 1,
					key: null,
					first_name: 'ali',
					middle_name: 'm',
					last_name: 'raza',
					dob: '2021-07-07',
					gender: 'x',
					age: null,
					ssn: null,
					cell_phone: '4444444444',
					home_phone: '1111111111',
					work_phone: null,
					height_ft: null,
					height_in: null,
					weight_lbs: null,
					weight_kg: null,
					meritial_status: null,
					profile_avatar: null,
					need_translator: 0,
					language: null,
					is_pregnant: null,
					is_law_enforcement_agent: null,
					status: 'open',
					notes: null,
					user_id: null,
					by_health_app: 0,
					creation_source: 1,
					created_by: null,
					updated_by: null,
					created_at: '2021-07-08T13:26:50.000Z',
					updated_at: '2021-07-08T13:26:50.000Z',
					deleted_at: null,
					pharmacy: [],
					self: {
						contact_information: {
							mail_address: {
								id: 1,
								key: null,
								contact_person_id: 1,
								type: 'mailing',
								street: '334 Amboy Ave',
								apartment: '123213123123123',
								latitude: null,
								longitude: null,
								city: 'Woodbridge Township',
								state: 'NJ',
								zip: '70950-1111',
								created_by: null,
								updated_by: null,
								created_at: '2021-07-08T13:26:50.000Z',
								updated_at: '2021-07-08T13:26:50.000Z',
								deleted_at: null,
							},
							residential_address: null,
						},
						id: 1,
						key: null,
						case_id: null,
						contact_person_type_id: 1,
						contact_person_relation_id: null,
						other_relation_description: null,
						first_name: null,
						middle_name: null,
						last_name: null,
						ssn: null,
						dob: null,
						age: null,
						gender: null,
						email: 'email@email.email',
						fax: null,
						cell_phone: '4444444444',
						home_phone: '1111111111',
						work_phone: null,
						ext: null,
						height_in: null,
						height_ft: null,
						weight_lbs: null,
						weight_kg: null,
						marital_status: null,
						is_resedential_same: null,
						is_form_filler: null,
						is_emergency: null,
						is_guarantor: null,
						workplace_name: null,
						object_id: 1,
						created_by: null,
						updated_by: null,
						created_at: '2021-07-08T13:26:50.000Z',
						updated_at: '2021-07-08T13:26:50.000Z',
						deleted_at: null,
					},
					emergency: {
						contact_person_relation: {
							name: 'Emeregeny Name',
						},
					},
					chart_id: '000-00-0001',
				},
			],
			pages: 1,
			total: 1,
		},
	};
	setPatientData = {
		id: null,
		first_name: 'first_name',
		middle_name: 'middle_name',
		last_name: 'last_name',
		gender: 'male',
		dob: '2021-05-22',
		ssn: '1122-2211',
		home_phone: '123456789',
		work_phone: '123456789',
		cell_phone: '123456789',
		email: 'admin@ovada.com',
		self: {
			id: 123,
			contact_information: {
				mail_address: {
					id: 20,
					street: 'street',
					apartment: 'apartment',
					city: 'city',
					zip: '123456',
					state: 'state',
				},
			},
		},
	};
	addPatientResponce = {
		status: 200,
		result: {
			data: {
				id: 1,
			},
		},
	};
	submitResponce = {
		status: 200,
		result: {
			data: {
				patient_exists: true,
				patient_id: 10,
				patient_personal: {
					id: 213,
				},
			},
		},
	};
	submitEmptyResponce = {
		status: 200,
		result: {},
	};
}
