export enum DoctorCalendarUrlsEnum {
	getAppointmentsOfAPatient = '/users/getAppointmentsOfAPatient',
	getAppointmentsOfAPatient_new='/appointments/get-patient-appointments',
	getAppointmentsOfAPatientV1_new='/appointments/get-patient-appointments-v1',
	getAllPatientAppointment='/appointments/get-all-patient-appointments',
	getAllPatientAppointmentV1='/appointments/get-all-patient-appointments-v1',
	getAllAppointmentsOfDoctor = '/user_facilities/getAllAppointmentsOfDoctor',
	getAppointmentsofDoctor='/appointments/get-doctor-appointments',
	// getDoctorInstructions = '/doctorInsForClinics/getDoctorInstructions',
	getDoctorInstructions='/doctor-instruction-for-facility/get', //  new 
	getPatient = 'patient/get-patient-speciality',
	get_checked_in_patients = 'case-patient-session/checked-in-patient',
	updateDoctorInstructions = '/doctorInsForClinics/updateDoctorInstructions',
	addDoctorinstructions = '/doctorInsForClinics/addDoctorinstructions',
	addDoctorInstruction_new='/doctor-instruction-for-facility/',
	deleteDocUnavail = '/doctorUnavailabilities/deleteDocUnavail',
	// addDoctorUnavailability = '/doctorUnavailabilities/addDoctorUnavailability',
	addDoctorUnavailability='/unavailable-doctors',
	deleteDoctorUnavailability='/unavailable-doctors',
	change_status = 'case-patient-session',
	changeAppointmentStatus = '/appointments/changeAppointmentStatus',
	changeAppointmentStatus_new = '/appointments/update-appointment-status',
	// getAppointmentPriority = '/appointment_priorities/getAppointmentPriority',
	getAppointmentPriority = '/appointment-priority/get-appointment-priority',
	// getAppointmentTypes = '/appointment_types/getAppointmentTypes',
	getAppointmentTypes = '/appointment-types/get-appointment-types',
	getDoctorAssignedPartial = '/docAssigns/getDoctorAssignedPartial',
	getPartialAvailableDoctors='/available-doctors/get-partial-available-doctors',
	getAllReturningCasesByPatient = 'patient/get-returning-cases?patient_id=',
	// updateAppointment = '/appointments',
	updateAppointment = '/appointments/v1',
	createVisitSession_manualApps = 'vd/visit_session/create',
	updateVisitSessionManualApps = 'vd/visitSession/update',
	caseDetail = 'case/details?id=',
	api_patients = '/kiosk_patients/patients?id=',
	getKioskPatientInfo='/kiosk/get-patient-info?',
	getPatientList = 'patient?pagination=1&filter=true&page=1&per_page=10&order=id&order_by=DESC&id=',
	getCaseList = 'case/get-case-ids?pagination=1&page=1&per_page=10&filter=1&order_by=ASC&id=',
	getCaseListWithoutParam = 'case/get-case-ids',
	getPatientsByCase = 'case/details?id=',
	getAllAppointmentsOfSpec = '/specAssigns/getAllAppointmentsOfSpec',
	checkInitial = '/appointments/checkInitial',
	checkInitialAppointment='/appointments/check-initial',
	updateEvaulationStatus = '/appointments/updateStatus',
	getSpecialityAppoinments='/appointments/get-speciality-appointments',
	visit_session_create = 'visit_session/create',
	getAppointmentById='/appointments',
	getMaxMinTimeOfFacility ='/users/max-min-time-of-facility ',
	specialtyVisitTypes='v2/specialty_visit_types',
	getCptListByVisitType="get/visit_type/cpt_codes",
	getpatientDetails='patient/get-bulk',
	get_physician_address='get/physician/address',
	appointments_get_patient_history ='/appointments/get-patient-history',
	appointmentsGetPatientHistoryCount ='/appointments/get-patient-history-count',
	getProviders='providers',
	getPatientListForChartID = 'patient',
	createMultiAppointWithCPTS = '/appointments/create-with-cptCodes' 
}


